"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { AlertTriangle, ArrowLeft, CircleCheck, ExternalLink, ListTodo, Loader2, RefreshCw } from "lucide-react"
import { OperationalHeader, OperationalMetric, OperationalMetricRail, OperationalPage, OperationalPanel, OperationalSectionHeader } from "@/components/app/operational-ui"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

type Priority = "critica" | "alta" | "media"
type CorroborationEvidence = { source:string; title:string; date:string|null; url:string|null; activity:string|null; directness:"direct"|"indirect"; matchedTerms:string[] }
type SourceCoverage = { source:string; available:boolean; evidenceCount:number }
type Corroboration = { status:"pending"|"running"|"completed"|"partial"|"failed"; evidenceState:"supporting_evidence"|"mixed_evidence"|"insufficient_evidence"|"not_observed"|null; newNiceClasses:number[]; activityTypes:string[]; evidence:CorroborationEvidence[]; sourceCoverage:SourceCoverage[]; lastError:string|null; completedAt:string|null }
type HypothesisEvidence = { source?:string; title?:string; activity?:string|null; directness?:"direct"|"indirect"; date?:string|null; url?:string|null }
type CompetitiveHypothesis = { id:string; signalEventId:string; status:"draft"|"accepted"|"rejected"; hypothesis:string; evidenceFor:HypothesisEvidence[]; evidenceMissing:string[]; evidenceAgainst:string[]; decisionReason:string|null; decidedBy:string|null; decidedAt:string|null; createdAt:string|null; updatedAt:string|null }
type AttentionItem = { key:string; signalKey:string; watchKey:string; title:string; subject:string; source:string; href:string; priority:Priority; reason:string; occurredAt:string|null; isNew:boolean; kind:"regulatory_case"|"competitive_expansion"|"new_high_signal"|"opportunity_conviction"; corroboration?:Corroboration|null }
type Summary = { total:number; critical:number; high:number; medium:number; opportunity:number; hypothesisReview:number }
type Member = { user_id:string; display_name:string; email:string; role:"owner"|"editor"|"viewer" }
type LinkedAction = { href:string; caseId:string; caseStatus:string; currentUserId:string; currentUserRole:"owner"|"editor"|"viewer"; members:Member[]; created?:{case?:boolean;evidence?:boolean;action?:boolean}; action:{ id:string; assigned_to:string|null; status:"open"|"done"; due_at:string|null; completed_at:string|null; outcome:string|null }; escalation:{ type:"owner_unassigned_critical"; createdAt:string }|null }
type AccountabilityState = "checking" | "none" | "overdue" | "unassigned" | "open" | "resolved"
type AccountabilitySummary = { overdue:number; unassigned:number; open:number; resolved:number }

const EMPTY:Summary={total:0,critical:0,high:0,medium:0,opportunity:0,hypothesisReview:0}
const EMPTY_ACCOUNTABILITY:AccountabilitySummary={overdue:0,unassigned:0,open:0,resolved:0}
const PRIORITY_LABEL:Record<Priority,string>={critica:"Crítica",alta:"Alta",media:"Media"}
const ACCOUNTABILITY_RANK:Record<AccountabilityState,number>={overdue:0,unassigned:1,none:2,open:3,checking:4,resolved:5}
const PRIORITY_RANK:Record<Priority,number>={critica:0,alta:1,media:2}
const ACTIVITY_LABEL:Record<string,string>={launching:"Lanzamiento",hiring:"Contratación",integrating:"Integración",commercializing:"Comercialización",patent:"Patente",research:"Investigación"}
const SOURCE_LABEL:Record<string,string>={google_news_rss:"Web / noticias",openalex:"OpenAlex",crossref:"Crossref",inapi_patents:"Patentes INAPI"}
const HYPOTHESIS_REVIEW_SOURCE="VIDENTIA · Seguimiento de hipótesis"

export default function ExecutiveAttentionPage(){
  const [items,setItems]=useState<AttentionItem[]>([])
  const [summary,setSummary]=useState<Summary>(EMPTY)
  const [accountability,setAccountability]=useState<Record<string,AccountabilityState>>({})
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState<string|null>(null)

  async function load(){setLoading(true);setError(null);try{const response=await fetch("/api/intelligence/watches/signals",{cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"No pudimos construir la cola ejecutiva.");setItems(Array.isArray(payload.attentionQueue)?payload.attentionQueue:[]);setSummary({...EMPTY,...(payload.attentionSummary??{})});setAccountability({})}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos construir la cola ejecutiva.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  const reportAccountability=useCallback((key:string,state:AccountabilityState)=>{setAccountability(current=>current[key]===state?current:{...current,[key]:state})},[])
  const ranked=useMemo(()=>[...items].sort((a,b)=>{const aState=accountability[a.key]??"checking";const bState=accountability[b.key]??"checking";const byAccountability=ACCOUNTABILITY_RANK[aState]-ACCOUNTABILITY_RANK[bState];if(byAccountability!==0)return byAccountability;const byPriority=PRIORITY_RANK[a.priority]-PRIORITY_RANK[b.priority];if(byPriority!==0)return byPriority;const aTime=a.occurredAt?Date.parse(a.occurredAt):0;const bTime=b.occurredAt?Date.parse(b.occurredAt):0;return bTime-aTime||a.key.localeCompare(b.key)}),[items,accountability])
  const accountabilitySummary=useMemo(()=>Object.values(accountability).reduce<AccountabilitySummary>((acc,state)=>{if(state==="overdue")acc.overdue+=1;else if(state==="unassigned")acc.unassigned+=1;else if(state==="open")acc.open+=1;else if(state==="resolved")acc.resolved+=1;return acc},{...EMPTY_ACCOUNTABILITY}),[accountability])
  const immediate=accountabilitySummary.overdue+accountabilitySummary.unassigned
  const headline=accountabilitySummary.overdue?`${accountabilitySummary.overdue} acción${accountabilitySummary.overdue===1?"":"es"} vencida${accountabilitySummary.overdue===1?"":"s"} requiere${accountabilitySummary.overdue===1?"":"n"} resolución.`:accountabilitySummary.unassigned?`${accountabilitySummary.unassigned} acción${accountabilitySummary.unassigned===1?"":"es"} crítica${accountabilitySummary.unassigned===1?"":"s"} necesita${accountabilitySummary.unassigned===1?"":"n"} responsable.`:summary.critical?`${summary.critical} señal${summary.critical===1?" crítica":"es críticas"} requiere${summary.critical===1?"":"n"} criterio ejecutivo.`:summary.hypothesisReview?`${summary.hypothesisReview} cambio${summary.hypothesisReview===1?"":"s"} material${summary.hypothesisReview===1?"":"es"} de hipótesis requiere${summary.hypothesisReview===1?"":"n"} revisión.`:summary.opportunity?`${summary.opportunity} cambio${summary.opportunity===1?"":"s"} material${summary.opportunity===1?"":"es"} de convicción requiere${summary.opportunity===1?"":"n"} revisión.`:summary.total?`${summary.total} caso${summary.total===1?"":"s"} permanece${summary.total===1?"":"n"} bajo atención.`:"No hay casos que requieran atención ejecutiva."

  return <OperationalPage>
    <OperationalHeader eyebrow="VIDENTIA / Atención ejecutiva" title={headline} description={<>Primero resuelve accountability vencido o sin dueño. Después revisa riesgo material, cambios en hipótesis competitivas, señales externas y cambios de convicción que puedan alterar una decisión humana.</>} meta={<><span>{summary.critical} críticos</span><span>{summary.high} altos</span><span>{summary.hypothesisReview} hipótesis</span><span>{summary.opportunity} tesis</span><span>{summary.medium} medios</span></>} actions={<div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link href="/monitorear"><ArrowLeft className="h-4 w-4"/>Monitorear</Link></Button><Button onClick={()=>void load()} disabled={loading}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<RefreshCw className="h-4 w-4"/>}Actualizar</Button></div>}/>

    <OperationalMetricRail>
      <OperationalMetric value={immediate} label="Para actuar" detail={`${accountabilitySummary.overdue} vencidas · ${accountabilitySummary.unassigned} sin responsable`} tone={immediate?"warning":"success"}/>
      <OperationalMetric value={accountabilitySummary.open} label="Abiertas" detail="Asignadas y dentro de plazo" tone={accountabilitySummary.open?"warning":"neutral"}/>
      <OperationalMetric value={summary.hypothesisReview} label="Hipótesis en revisión" detail="Cambio material detectado después de aceptación humana" tone={summary.hypothesisReview?"warning":"neutral"}/>
      <OperationalMetric value={accountabilitySummary.resolved} label="Resueltas" detail="Resultado ya registrado" tone={accountabilitySummary.resolved?"success":"neutral"}/>
    </OperationalMetricRail>

    <section className="py-9"><OperationalPanel>
      <OperationalSectionHeader eyebrow="01 / Cola ejecutiva" title={summary.total?`${summary.total} caso${summary.total===1?"":"s"} con atención activa`:"Sin casos que requieran atención"} meta="Accountability → materialidad / hipótesis / convicción → recencia"/>
      {error?<div role="alert" className="mt-5 border border-[#D6A46F]/20 bg-[#332C24]/70 p-4 text-sm text-[#E0B987]">{error}</div>:null}
      {loading?<div className="mt-5 flex items-center gap-2 border-y border-border/80 py-10 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>Calculando prioridad ejecutiva…</div>:ranked.length?<div className="mt-5 divide-y divide-border/80 border-y border-border/80">{ranked.map((item,index)=><AttentionRow key={item.key} item={item} index={index} visible={index<12} onAccountabilityChange={reportAccountability}/>)}</div>:<div className="mt-5 border-y border-border/80 py-10"><p className="font-medium text-white">No hay casos priorizados.</p></div>}
      {ranked.length>12?<p className="mt-4 text-xs text-muted-foreground">Mostrando los 12 casos con mayor urgencia operativa de {ranked.length}. Todos se consideran para el ranking y las métricas.</p>:null}
    </OperationalPanel></section>
  </OperationalPage>
}

function AttentionRow({item,index,visible,onAccountabilityChange}:{item:AttentionItem;index:number;visible:boolean;onAccountabilityChange:(key:string,state:AccountabilityState)=>void}){
  const [creating,setCreating]=useState(false)
  const [checking,setChecking]=useState(true)
  const [action,setAction]=useState<LinkedAction|null>(null)
  const [actionError,setActionError]=useState<string|null>(null)
  const external=item.href.startsWith("http")
  const title=truncate(actionTitle(item),240)

  async function loadActionState(created?:LinkedAction["created"]){setChecking(true);try{const params=new URLSearchParams({sourceId:item.signalKey,actionTitle:title});const response=await fetch(`/api/intelligence/actions?${params.toString()}`,{cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"No pudimos verificar la acción.");setAction(payload.linked?{...payload,created}:null)}catch(cause){setActionError(cause instanceof Error?cause.message:"No pudimos verificar la acción.")}finally{setChecking(false)}}
  useEffect(()=>{void loadActionState()},[item.signalKey,title])
  const accountabilityState=currentAccountabilityState(action,checking)
  useEffect(()=>{onAccountabilityChange(item.key,accountabilityState)},[item.key,accountabilityState,onAccountabilityChange])

  async function createAction(){if(creating||action)return;setCreating(true);setActionError(null);try{const dueAt=defaultDueAt(item.priority);const response=await fetch("/api/intelligence/actions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contextType:item.kind==="regulatory_case"?"company":"technology",contextQuery:item.subject,caseTitle:truncate(`${item.subject} · ${item.title}`,160),itemType:"alert",sourceId:item.signalKey,sourceTitle:truncate(item.title,240),actionTitle:title,priority:item.priority==="media"?"normal":"high",dueAt,assignedTo:null,evidence:{origin:"executive_attention",attentionKey:item.key,signalKey:item.signalKey,watchKey:item.watchKey,attentionKind:item.kind,attentionPriority:item.priority,source:item.source,sourceHref:item.href,reason:item.reason,occurredAt:item.occurredAt,suggestedDueAt:dueAt,corroboration:item.corroboration??null}})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"No pudimos crear la acción.");await loadActionState(payload.created)}catch(cause){setActionError(cause instanceof Error?cause.message:"No pudimos crear la acción.")}finally{setCreating(false)}}
  async function updateSchedule(assignedTo:string|null,dueAt:string|null){if(!action||action.action.status!=="open")return;setActionError(null);try{const response=await fetch("/api/cases/collaboration",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({type:"action_schedule",id:action.action.id,assignedTo,dueAt})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"No pudimos actualizar responsable o fecha.");await loadActionState(action.created)}catch(cause){setActionError(cause instanceof Error?cause.message:"No pudimos actualizar responsable o fecha.")}}

  const status=actionStatus(action)
  const assignee=action?.members.find(member=>member.user_id===action.action.assigned_to)
  const canAssign=action?.currentUserRole==="owner"||action?.currentUserRole==="editor"
  const priorityClass=item.priority==="critica"?"border-[#D6A46F]/30 bg-[#332C24]/80 text-[#E0B987]":item.priority==="alta"?"border-[#D6A46F]/20 bg-[#332C24]/55 text-[#E0B987]":""
  const kindLabel=item.source===HYPOTHESIS_REVIEW_SOURCE?"Hipótesis en revisión":item.kind==="regulatory_case"?"Caso regulatorio":item.kind==="competitive_expansion"?"Expansión competitiva":item.kind==="opportunity_conviction"?"Cambio de convicción":"Señal externa"

  return <article className={`${visible?"grid":"hidden"} gap-4 py-5 md:grid-cols-[64px_minmax(0,1fr)_auto] md:items-start`}>
    <div className="flex items-center gap-2 md:block"><span className="font-mono text-sm text-[#96B5A6]">{String(index+1).padStart(2,"0")}</span><AlertTriangle className="mt-2 hidden h-4 w-4 text-muted-foreground md:block"/></div>
    <div>
      <div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className={priorityClass}>{PRIORITY_LABEL[item.priority]}</Badge>{item.isNew?<Badge className="bg-[#173B37] text-[#96B5A6] hover:bg-[#173B37]">Nuevo</Badge>:null}<Badge variant="outline">{kindLabel}</Badge><Badge variant="outline">{checking?"Verificando acción":status}</Badge>{action?.escalation?<Badge variant="outline" className="border-[#D6A46F]/20 text-[#E0B987]">Escalada al owner</Badge>:null}</div>
      <h2 className="mt-3 text-sm font-medium leading-6 text-white">{item.title}</h2><p className="mt-1 text-xs text-[#96B5A6]">{item.subject} · {item.source}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{item.reason}</p>{item.occurredAt?<p className="mt-2 text-[11px] text-muted-foreground">Último movimiento · {formatDate(item.occurredAt)}</p>:null}{!action&&!checking?<p className="mt-2 text-xs text-muted-foreground">Sin acción · SLA sugerido {dueLabel(item.priority)}</p>:null}
      {item.kind==="competitive_expansion"?<CorroborationPanel signalKey={item.signalKey} corroboration={item.corroboration??null}/>:null}
      {action?<div className="mt-3 border-l-2 border-[#96B5A6]/35 pl-3"><p className="text-xs text-[#96B5A6]">Responsable · {assignee?.display_name||"Sin responsable"}</p><p className="mt-1 text-xs text-muted-foreground">Fecha límite · {action.action.due_at?formatDate(action.action.due_at):"Sin fecha"}</p>{action.escalation?<p className="mt-1 text-xs text-[#E0B987]">Escalada al owner · {formatDate(action.escalation.createdAt)}</p>:null}{action.created?<p className="mt-1 text-xs text-[#96B5A6]">{action.created?.action===false?"Acción existente recuperada":"Acción creada y vinculada a la evidencia"}</p>:null}{action.action.outcome?<p className="mt-2 text-xs leading-5 text-foreground/80">Resultado · {action.action.outcome}</p>:null}{canAssign&&action.action.status==="open"?<div className="mt-3 grid max-w-xl gap-2 sm:grid-cols-2"><select aria-label="Responsable" value={action.action.assigned_to??""} onChange={event=>void updateSchedule(event.target.value||null,action.action.due_at)} className="h-9 border border-input bg-background px-2 text-xs text-foreground"><option value="">Sin responsable</option>{action.members.map(member=><option key={member.user_id} value={member.user_id}>{member.display_name}</option>)}</select><Input aria-label="Fecha límite" type="datetime-local" value={toLocalDateTimeInput(action.action.due_at)} onChange={event=>void updateSchedule(action.action.assigned_to,event.target.value?new Date(event.target.value).toISOString():null)} className="h-9 text-xs"/></div>:null}</div>:null}
      {actionError?<p role="alert" className="mt-2 text-xs text-[#E0B987]">{actionError}</p>:null}
    </div>
    <div className="flex flex-wrap justify-end gap-2"><Button asChild variant="ghost" size="sm"><Link href={item.href} target={external?"_blank":undefined} rel={external?"noreferrer":undefined}>Evidencia{external?<ExternalLink className="h-3.5 w-3.5"/>:null}</Link></Button>{action?<Button asChild size="sm"><Link href={action.href}><CircleCheck className="h-3.5 w-3.5"/>Abrir acción</Link></Button>:<Button size="sm" onClick={()=>void createAction()} disabled={creating||checking}>{creating?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<ListTodo className="h-3.5 w-3.5"/>}Crear acción</Button>}</div>
  </article>
}

function CorroborationPanel({signalKey,corroboration}:{signalKey:string;corroboration:Corroboration|null}){
  const hypothesisReady=corroboration?.evidenceState==="supporting_evidence"
  const signalEventId=signalKey.startsWith("brand:")?signalKey.slice("brand:".length):""
  const [hypothesis,setHypothesis]=useState<CompetitiveHypothesis|null>(null)
  const [hypothesisLoading,setHypothesisLoading]=useState(false)
  const [hypothesisBusy,setHypothesisBusy]=useState(false)
  const [hypothesisError,setHypothesisError]=useState<string|null>(null)
  const [decisionReason,setDecisionReason]=useState("")

  useEffect(()=>{if(!hypothesisReady||!signalEventId)return;let cancelled=false;setHypothesisLoading(true);setHypothesisError(null);void fetch(`/api/intelligence/competitive-hypotheses?signalEventId=${encodeURIComponent(signalEventId)}`,{cache:"no-store"}).then(async response=>{const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"No pudimos cargar la hipótesis.");if(!cancelled)setHypothesis(payload.hypothesis??null)}).catch(cause=>{if(!cancelled)setHypothesisError(cause instanceof Error?cause.message:"No pudimos cargar la hipótesis.")}).finally(()=>{if(!cancelled)setHypothesisLoading(false)});return()=>{cancelled=true}},[hypothesisReady,signalEventId])

  async function formulateHypothesis(){if(!hypothesisReady||hypothesisBusy||hypothesis)return;setHypothesisBusy(true);setHypothesisError(null);try{const response=await fetch("/api/intelligence/competitive-hypotheses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({signalEventId})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"No pudimos formular la hipótesis.");setHypothesis(payload.hypothesis??null)}catch(cause){setHypothesisError(cause instanceof Error?cause.message:"No pudimos formular la hipótesis.")}finally{setHypothesisBusy(false)}}
  async function decideHypothesis(decision:"accepted"|"rejected"){if(!hypothesis||hypothesis.status!=="draft"||hypothesisBusy||decisionReason.trim().length<4)return;setHypothesisBusy(true);setHypothesisError(null);try{const response=await fetch("/api/intelligence/competitive-hypotheses",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:hypothesis.id,decision,reason:decisionReason.trim()})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"No pudimos guardar la decisión.");setHypothesis(payload.hypothesis??hypothesis);setDecisionReason("")}catch(cause){setHypothesisError(cause instanceof Error?cause.message:"No pudimos guardar la decisión.")}finally{setHypothesisBusy(false)}}

  if(!corroboration)return <div className="mt-4 border-l-2 border-border pl-3"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-medium text-foreground">Corroboración independiente</p><Badge variant="outline">Pendiente</Badge></div><p className="mt-1 text-xs leading-5 text-muted-foreground">La expansión registral ya fue detectada. La búsqueda independiente aún no tiene un resultado persistido.</p><BoundaryNote/></div>
  const state=corroborationState(corroboration)
  const coverage=corroboration.sourceCoverage
  const available=coverage.filter(item=>item.available).length
  const directEvidence=corroboration.evidence.filter(item=>item.directness==="direct")
  const topEvidence=corroboration.evidence.slice(0,4)
  return <div className="mt-4 border-l-2 border-[#96B5A6]/35 pl-3">
    <div className="flex flex-wrap items-center gap-2"><p className="text-xs font-medium text-foreground">Corroboración independiente</p><Badge variant="outline" className={state.tone}>{state.label}</Badge>{hypothesisReady?<Badge className="bg-[#173B37] text-[#96B5A6] hover:bg-[#173B37]">Apta para formular hipótesis</Badge>:null}</div>
    <p className="mt-1 max-w-3xl text-xs leading-5 text-muted-foreground">{state.detail}</p>
    {corroboration.newNiceClasses.length?<div className="mt-2 flex flex-wrap gap-1.5"><span className="mr-1 text-[11px] text-muted-foreground">Clases nuevas</span>{corroboration.newNiceClasses.map(value=><Badge key={value} variant="outline">Nice {value}</Badge>)}</div>:null}
    {corroboration.activityTypes.length?<div className="mt-2 flex flex-wrap gap-1.5">{corroboration.activityTypes.map(activity=><Badge key={activity} variant="outline">{ACTIVITY_LABEL[activity]??activity}</Badge>)}</div>:null}
    <div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-muted-foreground"><span>Fuentes disponibles · {available}/{coverage.length||0}</span><span>Evidencia directa · {directEvidence.length}</span>{corroboration.completedAt?<span>Última corroboración · {formatDate(corroboration.completedAt)}</span>:null}</div>
    {coverage.length?<div className="mt-2 flex flex-wrap gap-2">{coverage.map(item=><span key={item.source} className={`text-[11px] ${item.available?"text-[#96B5A6]":"text-muted-foreground"}`}>{SOURCE_LABEL[item.source]??item.source} · {item.available?`${item.evidenceCount} hallazgo${item.evidenceCount===1?"":"s"}`:"no disponible"}</span>)}</div>:null}
    {topEvidence.length?<div className="mt-3 divide-y divide-border/60 border-y border-border/60">{topEvidence.map((evidence,index)=><div key={`${evidence.source}:${evidence.title}:${index}`} className="py-2"><div className="flex flex-wrap items-center gap-2 text-[11px]"><span className="text-[#96B5A6]">{SOURCE_LABEL[evidence.source]??evidence.source}</span>{evidence.activity?<span className="text-muted-foreground">{ACTIVITY_LABEL[evidence.activity]??evidence.activity}</span>:null}{evidence.date?<span className="text-muted-foreground">{formatDate(evidence.date)}</span>:null}</div><div className="mt-1 flex items-start gap-2"><p className="min-w-0 flex-1 text-xs leading-5 text-foreground/85">{evidence.title}</p>{evidence.url?<Link href={evidence.url} target="_blank" rel="noreferrer" aria-label="Abrir evidencia independiente" className="mt-0.5 text-muted-foreground hover:text-foreground"><ExternalLink className="h-3.5 w-3.5"/></Link>:null}</div></div>)}</div>:null}
    {corroboration.status==="partial"&&corroboration.lastError?<p className="mt-2 text-[11px] text-[#E0B987]">Cobertura parcial · {corroboration.lastError}</p>:null}
    {hypothesisReady?<div className="mt-4 border-t border-border/70 pt-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-[10px] font-medium uppercase tracking-[0.14em] text-[#96B5A6]">Hipótesis competitiva</p><p className="mt-1 text-[11px] text-muted-foreground">Se formula sólo desde la corroboración persistida y requiere decisión humana explícita.</p></div>{hypothesis?.status?<Badge variant="outline" className={hypothesis.status==="accepted"?"border-[#96B5A6]/30 text-[#96B5A6]":hypothesis.status==="rejected"?"text-muted-foreground":""}>{hypothesis.status==="accepted"?"Aceptada":hypothesis.status==="rejected"?"Descartada":"Borrador"}</Badge>:null}</div>
      {hypothesisLoading?<p className="mt-3 inline-flex items-center gap-2 text-xs text-muted-foreground"><Loader2 className="h-3.5 w-3.5 animate-spin"/>Verificando hipótesis…</p>:!hypothesis?<Button className="mt-3" size="sm" variant="secondary" onClick={()=>void formulateHypothesis()} disabled={hypothesisBusy}>{hypothesisBusy?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:null}Formular hipótesis</Button>:<HypothesisReview hypothesis={hypothesis} reason={decisionReason} setReason={setDecisionReason} busy={hypothesisBusy} onDecision={decideHypothesis}/>} {hypothesisError?<p role="alert" className="mt-2 text-xs text-[#E0B987]">{hypothesisError}</p>:null}
    </div>:null}
    <BoundaryNote/>
  </div>
}

function HypothesisReview({hypothesis,reason,setReason,busy,onDecision}:{hypothesis:CompetitiveHypothesis;reason:string;setReason:(value:string)=>void;busy:boolean;onDecision:(decision:"accepted"|"rejected")=>Promise<void>}){
  return <div className="mt-3"><p className="max-w-3xl text-sm leading-6 text-foreground/90">{hypothesis.hypothesis}</p><div className="mt-3 grid gap-3 lg:grid-cols-3"><EvidenceColumn title="A favor" items={hypothesis.evidenceFor.map(item=>item.title||item.source||"Evidencia independiente")}/><EvidenceColumn title="Falta comprobar" items={hypothesis.evidenceMissing}/><EvidenceColumn title="En contra" items={hypothesis.evidenceAgainst} empty="Sin evidencia contraria explícita en esta corrida."/></div>{hypothesis.status==="draft"?<div className="mt-3"><textarea aria-label="Justificación de la decisión" value={reason} onChange={event=>setReason(event.target.value)} maxLength={1200} placeholder="Justifica brevemente por qué aceptar o descartar esta hipótesis…" className="min-h-20 w-full max-w-3xl border border-input bg-background p-3 text-xs leading-5 text-foreground outline-none focus-visible:ring-2 focus-visible:ring-ring/50"/><div className="mt-2 flex flex-wrap gap-2"><Button size="sm" onClick={()=>void onDecision("accepted")} disabled={busy||reason.trim().length<4}>{busy?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:null}Aceptar como hipótesis</Button><Button size="sm" variant="outline" onClick={()=>void onDecision("rejected")} disabled={busy||reason.trim().length<4}>Descartar</Button></div></div>:<div className="mt-3 border-l-2 border-border pl-3"><p className="text-xs text-muted-foreground">Decisión humana · {hypothesis.decidedAt?formatDate(hypothesis.decidedAt):"registrada"}</p>{hypothesis.decisionReason?<p className="mt-1 text-xs leading-5 text-foreground/80">{hypothesis.decisionReason}</p>:null}</div>}<p className="mt-3 text-[11px] leading-5 text-muted-foreground">Aceptar esta hipótesis no modifica conviction, prioridad ni lifecycle de oportunidad. Sólo registra una interpretación humana auditable sobre la evidencia observada.</p></div>
}

function EvidenceColumn({title,items,empty="Sin elementos."}:{title:string;items:string[];empty?:string}){return <div className="border border-border/60 p-3"><p className="text-[10px] font-medium uppercase tracking-[0.13em] text-muted-foreground">{title}</p>{items.length?<ul className="mt-2 space-y-1.5">{items.slice(0,6).map((item,index)=><li key={`${title}:${index}`} className="text-xs leading-5 text-foreground/80">{item}</li>)}</ul>:<p className="mt-2 text-xs leading-5 text-muted-foreground">{empty}</p>}</div>}
function BoundaryNote(){return <p className="mt-2 text-[11px] leading-5 text-muted-foreground">La corroboración aporta evidencia separada. No modifica conviction, prioridad ni decisión humana. Evidencia insuficiente no significa ausencia de actividad competitiva.</p>}
function corroborationState(value:Corroboration){if(value.status==="pending"||value.status==="running")return{label:"En búsqueda",detail:"VIDENTIA está buscando señales independientes de lanzamiento, contratación, integración, comercialización, patentes e investigación.",tone:""};if(value.status==="failed")return{label:"No disponible",detail:"La corroboración no pudo completarse; la expansión Nice permanece como señal registral sin inferencia adicional.",tone:"border-[#D6A46F]/20 text-[#E0B987]"};if(value.evidenceState==="supporting_evidence")return{label:"Evidencia encontrada",detail:"Hay señales independientes compatibles con actividad efectiva en el nuevo espacio. Corresponde revisión humana antes de formular una hipótesis competitiva.",tone:"border-[#96B5A6]/30 text-[#96B5A6]"};if(value.evidenceState==="mixed_evidence")return{label:"Señales parciales",detail:"Existen indicios independientes, pero aún no forman una corroboración suficiente para inferir entrada efectiva al mercado.",tone:"border-[#D6A46F]/20 text-[#E0B987]"};return{label:"Evidencia insuficiente",detail:"Las fuentes consultadas no aportan corroboración suficiente. Esto no constituye evidencia de ausencia de actividad competitiva.",tone:""}}
function currentAccountabilityState(value:LinkedAction|null,checking:boolean):AccountabilityState{if(checking)return "checking";if(!value)return "none";if(value.action.status==="done")return "resolved";if(value.action.due_at&&Date.parse(value.action.due_at)<Date.now())return "overdue";if(!value.action.assigned_to)return "unassigned";return "open"}
function actionStatus(value:LinkedAction|null){if(!value)return "Sin acción";if(value.action.status==="done")return "Acción resuelta";if(value.action.due_at&&Date.parse(value.action.due_at)<Date.now())return "Acción vencida";if(!value.action.assigned_to)return "Sin responsable";return "Acción abierta"}
function defaultDueAt(priority:Priority){const hours=priority==="critica"?24:priority==="alta"?48:24*7;return new Date(Date.now()+hours*60*60*1000).toISOString()}
function dueLabel(priority:Priority){return priority==="critica"?"24 horas":priority==="alta"?"48 horas":"7 días"}
function actionTitle(item:AttentionItem){return item.source===HYPOTHESIS_REVIEW_SOURCE?`Revisar cambio de hipótesis: ${item.title}`:item.kind==="regulatory_case"?`Resolver atención regulatoria: ${item.title}`:item.kind==="opportunity_conviction"?`Revisar cambio de convicción: ${item.title}`:`Revisar señal ejecutiva: ${item.title}`}
function truncate(value:string,max:number){return value.length<=max?value:value.slice(0,max-1).trimEnd()+"…"}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("es-CL",{dateStyle:"medium",timeStyle:"short"}).format(date)}
function toLocalDateTimeInput(value:string|null){if(!value)return "";const date=new Date(value);if(Number.isNaN(date.getTime()))return "";const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}