'use client'

import Link from 'next/link'
import { ArrowRight, CheckCircle2, Database, ImageIcon, Search, ShieldCheck, Sparkles } from 'lucide-react'
import { Button } from '@/components/ui/button'

const steps = [
  { icon: ImageIcon, label: '1 · Entrega la marca', title: 'Sube el logo o escribe el nombre.', copy: 'No necesitas elegir filtros, clase, estado o tipo de coincidencia antes de empezar.' },
  { icon: Search, label: '2 · N3uralia Intelligence investiga', title: 'Construimos la búsqueda por ti.', copy: 'Visual Compare ordena denominación, señales visuales, Niza, Viena y antecedentes oficiales INAPI.' },
  { icon: ShieldCheck, label: '3 · Revisa lo importante', title: 'Recibe antecedentes priorizados.', copy: 'Cada resultado explica por qué apareció y qué evidencia conviene revisar primero.' },
]

export default function LandingPage() {
  return <main className="min-h-screen bg-slate-950 text-white">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-slate-950/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex flex-col leading-none"><span className="text-lg font-semibold tracking-tight">N3uralia Intelligence</span><span className="mt-1 text-[10px] font-medium uppercase tracking-[0.18em] text-slate-500">Visual Compare</span></Link><div className="flex items-center gap-2"><Link href="/auth/login"><Button variant="ghost" className="text-slate-300 hover:bg-white/10 hover:text-white">Iniciar sesión</Button></Link><Link href="/demo"><Button className="gap-2 bg-white text-slate-950 hover:bg-slate-200">Probar con una marca <ArrowRight className="h-4 w-4" /></Button></Link></div></div></nav>

    <section className="relative overflow-hidden px-5 pb-24 pt-36 lg:px-8 lg:pb-32 lg:pt-44"><div className="pointer-events-none absolute left-1/2 top-0 h-[560px] w-[860px] -translate-x-1/2 rounded-full bg-blue-600/15 blur-[130px]"/><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-sm text-slate-300"><Sparkles className="h-4 w-4 text-blue-300"/> Visual Compare · Trademark Intelligence Chile</div><h1 className="max-w-5xl text-5xl font-semibold leading-[1.02] tracking-[-0.04em] sm:text-6xl lg:text-7xl">Buscar una marca debería ser <span className="text-blue-300">fácil.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">Sube un logo o escribe un nombre. Visual Compare, una capacidad de N3uralia Intelligence, transforma la complejidad registral en antecedentes claros y priorizados.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/demo"><Button size="lg" className="h-12 gap-2 bg-white px-6 text-slate-950 hover:bg-slate-200">Probar ahora · sin cuenta <ArrowRight className="h-4 w-4"/></Button></Link><Link href="#como-funciona"><Button size="lg" variant="outline" className="h-12 border-white/15 bg-transparent px-6 text-white hover:bg-white/10">Ver cómo funciona</Button></Link></div><p className="mt-4 text-sm text-slate-500">INAPI sigue siendo la fuente oficial. N3uralia Intelligence hace el trabajo de buscar, ordenar y priorizar.</p></div><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6 shadow-2xl shadow-blue-950/30"><p className="text-xs font-medium uppercase tracking-[0.18em] text-slate-500">Visual Compare</p><div className="mt-4 flex min-h-48 items-center justify-center rounded-2xl border border-dashed border-white/15 bg-slate-950/70 p-6 text-center"><div><ImageIcon className="mx-auto h-9 w-9 text-blue-300"/><p className="mt-4 font-medium">Logo, foto o nombre</p><p className="mt-2 text-sm text-slate-500">Una sola entrada. Sin decidir antes cómo consultar la base.</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Mini label="INAPI" value="Antecedentes"/><Mini label="Viena" value="Señales visuales"/><Mini label="Niza" value="Clases"/></div></div></div></section>

    <section id="como-funciona" className="border-y border-white/10 bg-white/[0.025] px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mb-12 max-w-3xl"><p className="text-sm font-medium uppercase tracking-[0.2em] text-blue-300">Menos formulario. Más respuesta.</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">El usuario entrega la marca. N3uralia Intelligence hace la búsqueda.</h2><p className="mt-5 text-lg leading-7 text-slate-400">El abogado conserva la decisión. La plataforma elimina el trabajo mecánico que ocurre antes.</p></div><div className="grid gap-4 lg:grid-cols-3">{steps.map(({icon:Icon,label,title,copy})=><article key={label} className="rounded-2xl border border-white/10 bg-slate-900/60 p-7"><div className="mb-8 flex h-11 w-11 items-center justify-center rounded-xl border border-white/10 bg-white/5"><Icon className="h-5 w-5 text-blue-300"/></div><p className="text-sm font-medium text-blue-300">{label}</p><h3 className="mt-2 text-2xl font-semibold tracking-tight">{title}</h3><p className="mt-4 text-sm leading-6 text-slate-400">{copy}</p></article>)}</div></div></section>

    <section className="px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-medium uppercase tracking-[0.2em] text-blue-300">Evidencia antes que opinión</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">Cada antecedente explica por qué está ahí.</h2><p className="mt-5 max-w-xl leading-7 text-slate-400">Solicitud, registro, titular, estado y clases permanecen visibles. La relevancia calculada se presenta separada de cualquier interpretación asistida.</p></div><div className="grid gap-3 sm:grid-cols-2"><Fact icon={Database} title="Registro" copy="Datos registrales en una ficha legible."/><Fact icon={ImageIcon} title="Imagen" copy="Elementos visuales y clasificación figurativa."/><Fact icon={ShieldCheck} title="Prioridad" copy="Por qué merece revisión, sin fingir certeza jurídica."/><Fact icon={CheckCircle2} title="Trazabilidad" copy="Fuente y momento de consulta visibles."/></div></div></section>

    <section className="border-y border-white/10 bg-white/[0.025] px-5 py-16 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-3xl"><p className="text-xs font-medium uppercase tracking-[0.2em] text-slate-500">La plataforma detrás de Visual Compare</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">N3uralia Intelligence</h2><p className="mt-3 leading-7 text-slate-400">Inteligencia aplicada para transformar fuentes complejas en búsqueda, evidencia, priorización y operación. Desarrollado por N3uralia.</p></div><a href="https://www.n3uralia.com" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-medium text-blue-300 hover:text-blue-200">Conocer N3uralia <ArrowRight className="h-4 w-4"/></a></div></section>

    <section className="px-5 py-24 text-center lg:px-8"><div className="mx-auto max-w-4xl"><h2 className="text-4xl font-semibold tracking-tight sm:text-5xl">Pruébalo antes de crear una cuenta.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-7 text-slate-400">Una marca, una imagen o ambas. La primera búsqueda no requiere aprender cómo funciona INAPI.</p><Link href="/demo"><Button size="lg" className="mt-8 h-12 gap-2 bg-white px-6 text-slate-950 hover:bg-slate-200">Probar Visual Compare <ArrowRight className="h-4 w-4"/></Button></Link></div></section>
    <footer className="border-t border-white/10 px-5 py-8 text-sm text-slate-500 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-slate-300">N3uralia Intelligence</p><p className="mt-1">Visual Compare · Powered by <a href="https://www.n3uralia.com" target="_blank" rel="noreferrer" className="text-slate-300 hover:text-white">N3uralia</a></p></div><span>Apoya investigación y no reemplaza evaluación jurídica profesional.</span></div></footer>
  </main>
}

function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white/[0.04] p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm">{value}</p></div>}
function Fact({icon:Icon,title,copy}:{icon:typeof Database;title:string;copy:string}){return <div className="rounded-xl border border-white/10 bg-white/[0.03] p-5"><Icon className="h-5 w-5 text-slate-300"/><h3 className="mt-4 font-medium">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{copy}</p></div>}
