import Link from "next/link"
import { ArrowRight, Fingerprint, ImageIcon, Search, ShieldCheck } from "lucide-react"
import { Button } from "@/components/ui/button"
import { localePath, type PublicLocale } from "@/lib/marketing-locale"

const endpoints = [
  ["GET", "/api/v1/health", "Public", "curl \"$BASE_URL/api/v1/health\""],
  ["GET", "/api/v1/trademarks/search", "Bearer API key", "curl \"$BASE_URL/api/v1/trademarks/search?q=$QUERY&type=nombre\" -H \"Authorization: Bearer $API_KEY\""],
  ["POST", "/api/v1/images", "Bearer API key", "curl -X POST \"$BASE_URL/api/v1/images\" -H \"Authorization: Bearer $API_KEY\" -F \"image=@$IMAGE_PATH\""],
  ["POST", "/api/v1/compare", "Bearer API key", "curl -X POST \"$BASE_URL/api/v1/compare\" -H \"Authorization: Bearer $API_KEY\" -H \"Content-Type: application/json\""],
] as const

const copy = {
  es: {
    tagline: "API EMPRESARIAL · CHILE", title: "Integra inteligencia marcaria sin depender de la interfaz.", body: "Documentación técnica para equipos que necesitan integrar búsqueda, imágenes y comparación marcaria en sistemas empresariales. El acceso API se define después de revisar el caso de uso.", enterprise: "Solicitar acceso empresarial", demo: "Probar VIDENTIA", capabilities: "CAPACIDADES VERIFICADAS", contract: "CONTRATO API", contractTitle: "Rutas disponibles para integración empresarial.", contractBody: "Las operaciones protegidas usan API key, cuota y medición. La búsqueda web interna no forma parte de este contrato público.", footer: "VIDENTIA · API empresarial para Chile", capabilityItems: [["Búsqueda marcaria", "Nombre, Niza y Viena con filtros verificables."], ["Ingesta de imágenes", "Procesamiento técnico y deduplicación por hash."], ["Comparación", "Similitud, OCR, EXIF, ELA y señales forenses disponibles."], ["Control comercial", "API key, cuotas y registro de consumo en operaciones protegidas."]], descriptions: ["Estado del servicio y frescura de sincronizaciones INAPI.", "Búsqueda comercial de marcas por nombre, Niza o Viena, con filtros, cuota y medición de uso.", "Ingesta de una imagen real con SHA-256, pHash, metadatos y deduplicación.", "Compara dos imágenes previamente incorporadas y devuelve señales técnicas y contexto disponible."],
  },
  en: {
    tagline: "ENTERPRISE API · CHILE", title: "Integrate trademark intelligence without depending on the interface.", body: "Technical documentation for teams integrating trademark search, images and comparison into enterprise systems. API access is defined after reviewing the use case.", enterprise: "Request enterprise access", demo: "Try VIDENTIA", capabilities: "VERIFIED CAPABILITIES", contract: "API CONTRACT", contractTitle: "Routes available for enterprise integration.", contractBody: "Protected operations use API keys, quotas and usage metering. VIDENTIA's internal web search is not part of this public contract.", footer: "VIDENTIA · Enterprise API for Chile", capabilityItems: [["Trademark search", "Name, Nice and Vienna with verifiable filters."], ["Image ingestion", "Technical processing and hash-based deduplication."], ["Comparison", "Similarity, OCR, EXIF, ELA and available forensic signals."], ["Commercial controls", "API keys, quotas and consumption records for protected operations."]], descriptions: ["Service status and INAPI synchronization freshness.", "Commercial trademark search by name, Nice or Vienna with filters, quota and usage metering.", "Ingest a real image with SHA-256, pHash, metadata and deduplication.", "Compare two previously ingested images and return technical signals and available context."],
  },
} as const

const icons = [Search, ImageIcon, Fingerprint, ShieldCheck] as const

export function LocalizedDocsPage({ locale }: { locale: PublicLocale }) {
  const t = copy[locale]
  return <main className="min-h-screen bg-[#F7F8F6] text-[#111827]">
    <nav className="sticky top-0 z-50 border-b border-black/10 bg-[#F7F8F6]/95"><div className="mx-auto flex h-[72px] max-w-[1480px] items-center justify-between px-5 lg:px-10"><Link href={localePath(locale)} className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-[10px] bg-[#111827] text-sm font-semibold text-white">V</span><span><span className="block text-[15px] font-semibold tracking-[0.16em]">VIDENTIA</span><span className="mt-1 block text-[9px] uppercase tracking-[0.18em] text-[#475569]">by N3uralia</span></span></Link><Button asChild className="h-10 rounded-lg bg-[#111827] px-5 text-white shadow-none hover:bg-[#273244]"><Link href={localePath(locale, "/acceso-empresarial")}>{t.enterprise}</Link></Button></div></nav>
    <section className="border-b border-black/10 px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1480px] gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#0F766E]">{t.tagline}</p><h1 className="mt-6 max-w-4xl text-[clamp(3rem,6vw,6.2rem)] font-normal leading-[0.95] tracking-[-0.055em]">{t.title}</h1></div><div className="max-w-2xl lg:justify-self-end"><p className="text-lg leading-8 text-[#667085]">{t.body}</p><div className="mt-7 flex gap-3"><Button asChild className="h-11 gap-2 rounded-lg bg-[#0F766E] px-5 text-white shadow-none hover:bg-[#134E4A]"><Link href={localePath(locale, "/acceso-empresarial")}>{t.enterprise}<ArrowRight className="h-4 w-4" /></Link></Button><Button asChild variant="outline" className="h-11 rounded-lg border-black/15 bg-transparent px-5"><Link href={localePath(locale, "/demo")}>{t.demo}</Link></Button></div></div></div></section>
    <section className="bg-[#111827] px-5 py-20 text-white lg:px-10 lg:py-24"><div className="mx-auto max-w-[1480px]"><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#63C7B8]">{t.capabilities}</p><div className="mt-10 grid border-y border-white/15 md:grid-cols-2 lg:grid-cols-4">{t.capabilityItems.map(([title, text], index) => { const Icon = icons[index]; return <article key={title} className={`py-8 lg:px-7 ${index > 0 ? "lg:border-l lg:border-white/15" : ""}`}><Icon className="h-5 w-5 text-[#63C7B8]" /><h2 className="mt-7 text-lg font-medium">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p></article> })}</div></div></section>
    <section className="px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1480px]"><div className="grid gap-8 border-b border-black/10 pb-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#0F766E]">{t.contract}</p><h2 className="mt-4 text-[clamp(2.3rem,4vw,4.5rem)] font-normal leading-[1.02] tracking-[-0.045em]">{t.contractTitle}</h2></div><p className="max-w-2xl text-lg leading-8 text-[#667085] lg:justify-self-end">{t.contractBody}</p></div><div className="divide-y divide-black/10 border-b border-black/10">{endpoints.map((item, index) => <article key={item[1]} className="grid gap-6 py-8 lg:grid-cols-[70px_1fr_1.2fr]"><span className="font-mono text-[11px] text-[#0F766E]">0{index + 1}</span><div><div className="flex items-center gap-2"><span className="rounded-md bg-[#111827] px-2.5 py-1 font-mono text-[11px] font-semibold text-white">{item[0]}</span><span className="text-xs text-[#667085]">{item[2]}</span></div><h3 className="mt-4 font-mono text-lg font-semibold">{item[1]}</h3><p className="mt-3 text-sm leading-6 text-[#667085]">{t.descriptions[index]}</p></div><pre tabIndex={0} className="overflow-x-auto rounded-xl border border-black/10 bg-[#EEF1EE] p-4 text-xs leading-6 text-[#344054]"><code>{item[3]}</code></pre></article>)}</div></div></section>
    <footer className="border-t border-black/10 px-5 py-8 lg:px-10"><div className="mx-auto flex max-w-[1480px] flex-col gap-3 text-xs text-[#667085] sm:flex-row sm:items-center sm:justify-between"><span>{t.footer}</span><span>{locale === "es" ? "Un desarrollo de N3uralia" : "Developed by N3uralia"}</span></div></footer>
  </main>
}
