import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { localePath, type PublicLocale } from "@/lib/marketing-locale"

type LegalKind = "privacy" | "terms"

const content = {
  privacy: {
    es: {
      eyebrow: "Legal · Privacidad",
      title: "Política de privacidad",
      updated: "Última actualización: 24 de agosto de 2026. Esta página describe el tratamiento de información en el sitio público y en las interacciones comerciales de VIDENTIA.",
      other: "Términos de uso",
      sections: [
        ["1. Alcance", ["Esta política explica cómo VIDENTIA, un desarrollo de N3uralia, trata información cuando utilizas videntia.app, incluida la demostración pública de investigación marcaria.", "La demostración está orientada a marcas, productos, servicios e imágenes de signos distintivos. No está diseñada para recibir datos personales sensibles ni información confidencial de terceros. Evita incorporar ese tipo de información en los campos o imágenes que envíes."]],
        ["2. Información que puede procesarse", ["Cuando utilizas la demo podemos procesar el nombre de la marca, la descripción opcional de productos o servicios, una imagen opcional y los datos técnicos necesarios para recibir y responder la solicitud.", "Para limitar el abuso de la demostración se utiliza una identidad técnica derivada de la dirección IP y del user-agent. El mecanismo de cuota transforma esa combinación mediante HMAC antes de registrarla; la clave almacenada no contiene la IP ni el user-agent en texto legible.", "También podemos procesar métricas de navegación y eventos operativos agregados para entender el uso y rendimiento del sitio. Los eventos no incluyen el nombre de la marca, el texto de actividad ni la imagen enviada.", "Si nos contactas o solicitas acceso empresarial, trataremos además la información que voluntariamente entregues para responder, preparar una propuesta, gestionar la relación comercial o prestar el servicio solicitado."]],
        ["3. Finalidades", ["Usamos la información para ejecutar la investigación solicitada, analizar señales denominativas o figurativas, sugerir clases cuando existe contexto, consultar o contrastar fuentes, prevenir abuso, mantener seguridad y disponibilidad, diagnosticar fallos, medir de forma agregada el uso del producto y responder solicitudes comerciales o de soporte.", "No utilizamos la demo pública para emitir una decisión jurídica automatizada sobre registrabilidad. Los resultados son apoyo a la investigación y deben contrastarse con las fuentes oficiales y, cuando corresponda, con asesoría profesional."]],
        ["4. Proveedores y fuentes externas", ["VIDENTIA utiliza proveedores tecnológicos necesarios para operar infraestructura, almacenamiento, seguridad, analítica y procesamiento automatizado. Una solicitud o señal técnica puede ser transmitida a esos proveedores únicamente en la medida necesaria para ejecutar la función solicitada u operar el servicio.", "La plataforma también consulta, sincroniza o contrasta información de fuentes externas relacionadas con propiedad industrial. La disponibilidad y exactitud de esas fuentes dependen de sus respectivos operadores."]],
        ["5. Conservación", ["La demo pública no está concebida como un expediente persistente del usuario. Sin embargo, información técnica o de operación puede conservarse durante el tiempo razonablemente necesario para seguridad, prevención de abuso, diagnóstico, medición agregada, cumplimiento y continuidad del servicio.", "Cuando una investigación se convierte en una cuenta, caso, contrato o solicitud comercial, la información asociada puede conservarse durante la relación y posteriormente por los plazos necesarios para cumplir obligaciones legales, contractuales, contables o de defensa de derechos."]],
        ["6. Seguridad", ["Aplicamos medidas técnicas y organizativas razonables para reducir el riesgo de acceso, alteración, pérdida o uso no autorizado. Ningún sistema conectado a Internet puede garantizar riesgo cero.", "Los límites de tamaño, tipo de archivo, validaciones de entrada, controles de cuota y separación entre funciones públicas y autenticadas forman parte de las medidas operativas de la demo."]],
        ["7. Derechos y solicitudes", ["Puedes solicitar información sobre datos personales que mantengamos asociados a ti y ejercer los derechos que correspondan conforme a la legislación chilena aplicable. Para ello, escribe a info@n3uralia.com indicando que tu solicitud se refiere a privacidad en VIDENTIA.", "Podremos solicitar verificación razonable de identidad antes de responder una solicitud que implique acceso, rectificación, eliminación u otra operación sobre datos personales."]],
        ["8. Marco normativo y cambios", ["Esta política se interpreta conforme a la normativa chilena aplicable sobre protección de datos y vida privada. La Ley 19.628 se mantiene vigente en su régimen actual hasta el 30 de noviembre de 2026; las modificaciones introducidas por la Ley 21.719 tienen vigencia diferida desde el 1 de diciembre de 2026.", "Podemos actualizar esta política cuando cambie la operación, la tecnología o el marco regulatorio. La versión publicada en esta página indicará la fecha de última actualización."]],
      ],
    },
    en: {
      eyebrow: "Legal · Privacy",
      title: "Privacy policy",
      updated: "Last updated: August 24, 2026. This page describes how information is processed on VIDENTIA's public site and in commercial interactions.",
      other: "Terms of use",
      sections: [
        ["1. Scope", ["This policy explains how VIDENTIA, a product developed by N3uralia, processes information when you use videntia.app, including the public trademark research demonstration.", "The demonstration is intended for trademarks, products, services and images of distinctive signs. It is not designed to receive sensitive personal data or confidential third-party information. Avoid including that type of information in submitted fields or images."]],
        ["2. Information that may be processed", ["When you use the demo, we may process the trademark name, an optional description of goods or services, an optional image and technical data required to receive and respond to the request.", "To limit abuse, the demonstration uses a technical identity derived from the IP address and user agent. The quota mechanism transforms that combination with HMAC before recording it; the stored quota key does not contain the IP address or user agent in readable form.", "We may also process aggregated navigation metrics and operational events to understand site use and performance. Demo events do not include the trademark name, activity text or submitted image.", "If you contact us or request enterprise access, we also process information you voluntarily provide to respond, prepare a proposal, manage the commercial relationship or provide the requested service."]],
        ["3. Purposes", ["We use information to perform the requested research, analyze word or figurative signals, suggest classes when context is available, query or compare information sources, prevent abuse, maintain security and availability, diagnose failures, measure product use in aggregate and respond to commercial or support requests.", "We do not use the public demo to issue an automated legal decision on registrability. Results support research and should be checked against official sources and, where appropriate, professional advice."]],
        ["4. Providers and external sources", ["VIDENTIA uses technology providers required for infrastructure, storage, security, analytics and automated processing. A request or technical signal may be transmitted to those providers only to the extent required to perform the requested function or operate the service.", "The platform also queries, synchronizes or compares information from external industrial-property sources. Availability and accuracy of those sources depend on their respective operators."]],
        ["5. Retention", ["The public demo is not intended to be a persistent user file. Technical or operational information may nevertheless be retained for the period reasonably necessary for security, abuse prevention, diagnostics, aggregate measurement, compliance and service continuity.", "When research becomes associated with an account, case, contract or commercial request, related information may be retained during the relationship and afterwards for periods required by legal, contractual, accounting or rights-defense obligations."]],
        ["6. Security", ["We apply reasonable technical and organizational measures to reduce the risk of unauthorized access, alteration, loss or use. No internet-connected system can guarantee zero risk.", "File size and type limits, input validation, quota controls and separation between public and authenticated functions form part of the demo's operational safeguards."]],
        ["7. Rights and requests", ["You may request information about personal data we maintain in relation to you and exercise rights available under applicable Chilean law. Write to info@n3uralia.com and indicate that the request concerns VIDENTIA privacy.", "We may request reasonable identity verification before responding to a request involving access, correction, deletion or another operation on personal data."]],
        ["8. Legal framework and changes", ["This policy is interpreted under applicable Chilean privacy and data-protection law. Law 19,628 remains in force under its current regime through November 30, 2026; amendments introduced by Law 21,719 take effect on December 1, 2026.", "We may update this policy when operations, technology or the regulatory framework change. The version published here will state its latest update date."]],
      ],
    },
  },
  terms: {
    es: {
      eyebrow: "Legal · Uso",
      title: "Términos de uso",
      updated: "Última actualización: 24 de agosto de 2026. Estas condiciones aplican al uso del sitio público y de la demostración de VIDENTIA.",
      other: "Política de privacidad",
      sections: [
        ["1. Servicio", ["VIDENTIA es una plataforma de apoyo a la investigación marcaria desarrollada por N3uralia. El sitio público permite explorar una demostración limitada y conocer el acceso empresarial.", "Las funcionalidades autenticadas, integraciones, niveles de servicio, soporte, volumen, vigilancia y demás condiciones comerciales se rigen adicionalmente por la propuesta, orden de servicio o contrato que corresponda."]],
        ["2. Naturaleza de los resultados", ["VIDENTIA organiza señales, antecedentes y contexto para facilitar una revisión. No otorga, deniega ni garantiza el registro de una marca y no sustituye una decisión de INAPI, de tribunales, de otra autoridad competente ni el análisis de un profesional especializado.", "Una coincidencia, similitud, clase, código, score, alerta o recomendación no constituye por sí sola una conclusión jurídica. Que un antecedente no aparezca en una consulta no garantiza inexistencia de conflicto, prioridad, disponibilidad o registrabilidad."]],
        ["3. Fuentes y actualidad", ["VIDENTIA puede combinar información sincronizada, verificaciones en línea y procesamiento automatizado. Los datos provenientes de terceros pueden contener retrasos, omisiones, cambios de formato, indisponibilidad o errores ajenos a N3uralia.", "Antes de adoptar una decisión jurídica, comercial o de presentación debes contrastar la información relevante con la fuente oficial vigente y realizar la revisión profesional que corresponda."]],
        ["4. Demo pública", ["La demo es una vista limitada y puede restringir cantidad de consultas, estrategias de búsqueda, antecedentes visibles, tiempo de ejecución, tamaño o tipo de imágenes y otras capacidades. Estos límites pueden cambiar para proteger la estabilidad y seguridad del servicio.", "No debes utilizar la demo para cargar material ilícito, malware, secretos, credenciales, datos personales sensibles ni información cuya transmisión o tratamiento no estés autorizado a realizar."]],
        ["5. Uso permitido", ["Puedes utilizar VIDENTIA para fines lícitos de investigación, evaluación, gestión y vigilancia de propiedad industrial dentro del alcance habilitado para tu modalidad de acceso.", "No está permitido eludir controles de acceso o cuota, interferir con el servicio, intentar obtener credenciales o datos no autorizados, introducir código malicioso, automatizar consumo abusivo, revender accesos sin autorización o utilizar el servicio de una forma que infrinja derechos de terceros o la legislación aplicable."]],
        ["6. Contenidos enviados", ["Conservas los derechos que te correspondan sobre el material que envías. Al utilizar una función que requiere procesarlo, autorizas el tratamiento técnico necesario para ejecutar esa función, incluyendo análisis automatizado y transmisión a proveedores tecnológicos cuando sea necesario para prestar el servicio.", "Eres responsable de contar con autorización suficiente para enviar el contenido y de no incorporar información innecesaria de terceros. La demo no debe usarse como repositorio de documentación confidencial."]],
        ["7. Propiedad intelectual", ["La marca VIDENTIA, su interfaz, software, diseño, documentación, métodos de presentación y demás componentes propios están protegidos por los derechos que correspondan a N3uralia o a sus licenciantes. Estos términos no transfieren propiedad intelectual sobre la plataforma.", "Los antecedentes provenientes de fuentes externas mantienen el régimen jurídico y atribución que les corresponda."]],
        ["8. Disponibilidad y cambios", ["Podemos modificar, suspender o limitar funciones públicas cuando sea necesario por mantenimiento, seguridad, cambios de proveedor, restricciones de una fuente externa, mejoras del producto o cumplimiento normativo.", "Para servicios contratados, los compromisos específicos de disponibilidad, soporte o continuidad serán los establecidos en el acuerdo comercial aplicable."]],
        ["9. Responsabilidad", ["Debes ejercer criterio propio respecto de los resultados y verificar los antecedentes relevantes antes de actuar. En la máxima medida permitida por la ley, N3uralia no responde por decisiones tomadas exclusivamente sobre la base de una vista de demostración, por indisponibilidad o errores atribuibles a fuentes externas, ni por un uso del servicio contrario a estos términos.", "Nada en estos términos pretende excluir responsabilidades que no puedan limitarse válidamente conforme a la legislación aplicable."]],
        ["10. Contacto y actualizaciones", ["Para consultas sobre estos términos puedes escribir a info@n3uralia.com. Podemos actualizar estas condiciones para reflejar cambios del producto, seguridad, operación o normativa.", "Estos términos se interpretan conforme a la legislación de la República de Chile, sin perjuicio de las normas imperativas y reglas de competencia que resulten aplicables en cada caso."]],
      ],
    },
    en: {
      eyebrow: "Legal · Use",
      title: "Terms of use",
      updated: "Last updated: August 24, 2026. These terms apply to the public site and VIDENTIA demonstration.",
      other: "Privacy policy",
      sections: [
        ["1. Service", ["VIDENTIA is a trademark research support platform developed by N3uralia. The public site lets users explore a limited demonstration and learn about enterprise access.", "Authenticated features, integrations, service levels, support, volume, monitoring and other commercial conditions are additionally governed by the applicable proposal, service order or contract."]],
        ["2. Nature of results", ["VIDENTIA organizes signals, prior rights and context to facilitate review. It does not grant, deny or guarantee trademark registration and does not replace a decision by INAPI, courts, another competent authority or analysis by a specialized professional.", "A match, similarity, class, code, score, alert or recommendation does not by itself constitute a legal conclusion. The absence of a record from a query does not guarantee absence of conflict, priority, availability or registrability."]],
        ["3. Sources and currency", ["VIDENTIA may combine synchronized information, online verification and automated processing. Third-party data may contain delays, omissions, format changes, unavailability or errors outside N3uralia's control.", "Before making a legal, commercial or filing decision, you should verify relevant information against the current official source and obtain the professional review appropriate to the situation."]],
        ["4. Public demo", ["The demo is a limited view and may restrict the number of queries, search strategies, visible records, execution time, image size or type and other capabilities. Limits may change to protect service stability and security.", "You must not use the demo to upload unlawful material, malware, secrets, credentials, sensitive personal data or information you are not authorized to transmit or process."]],
        ["5. Permitted use", ["You may use VIDENTIA for lawful industrial-property research, evaluation, management and monitoring within the scope enabled for your access level.", "You may not bypass access or quota controls, interfere with the service, attempt to obtain unauthorized credentials or data, introduce malicious code, automate abusive consumption, resell access without authorization or use the service in a manner that infringes third-party rights or applicable law."]],
        ["6. Submitted content", ["You retain rights you hold in material you submit. By using a function that requires processing, you authorize the technical processing necessary to perform that function, including automated analysis and transmission to technology providers when necessary to provide the service.", "You are responsible for having sufficient authorization to submit content and for not including unnecessary third-party information. The demo must not be used as a repository for confidential documentation."]],
        ["7. Intellectual property", ["The VIDENTIA trademark, interface, software, design, documentation, presentation methods and other proprietary components are protected by rights held by N3uralia or its licensors. These terms do not transfer intellectual property in the platform.", "Records originating from external sources remain subject to their applicable legal regime and attribution."]],
        ["8. Availability and changes", ["We may modify, suspend or limit public functions when necessary for maintenance, security, provider changes, restrictions imposed by an external source, product improvements or regulatory compliance.", "For contracted services, specific availability, support or continuity commitments are those established in the applicable commercial agreement."]],
        ["9. Liability", ["You should exercise independent judgment regarding results and verify relevant records before acting. To the maximum extent permitted by law, N3uralia is not responsible for decisions made solely on the basis of a demonstration view, for unavailability or errors attributable to external sources, or for use contrary to these terms.", "Nothing in these terms is intended to exclude liabilities that cannot validly be limited under applicable law."]],
        ["10. Contact and updates", ["For questions about these terms, write to info@n3uralia.com. We may update these conditions to reflect changes in the product, security, operations or regulation.", "These terms are interpreted under the laws of the Republic of Chile, without prejudice to mandatory rules and jurisdiction provisions applicable in each case."]],
      ],
    },
  },
} as const

export function LocalizedLegalPage({ locale, kind }: { locale: PublicLocale; kind: LegalKind }) {
  const page = content[kind][locale]
  const otherPath = kind === "privacy" ? "/terminos" : "/privacidad"
  return (
    <main className="min-h-screen bg-[#090D12] text-[#F4F7F6]">
      <header className="border-b border-white/10 px-5 py-5 lg:px-10"><div className="mx-auto flex max-w-[980px] items-center justify-between gap-6"><Link href={localePath(locale)} className="inline-flex items-center gap-2 text-sm text-[#8F9AA8] transition hover:text-white"><ArrowLeft className="h-4 w-4" />{locale === "es" ? "Volver a VIDENTIA" : "Back to VIDENTIA"}</Link><div className="text-right"><p className="text-sm font-semibold tracking-[0.14em] text-white">VIDENTIA</p><p className="mt-1 text-[9px] uppercase tracking-[0.18em] text-[#8994A1]">by N3uralia</p></div></div></header>
      <article className="px-5 py-14 lg:px-10 lg:py-20"><div className="mx-auto max-w-[980px]"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#64D5C2]">{page.eyebrow}</p><h1 className="mt-5 text-[clamp(2.8rem,6vw,5.4rem)] font-normal leading-[0.95] tracking-[-0.055em] text-white">{page.title}</h1><p className="mt-6 max-w-3xl text-base leading-7 text-[#9AA6B2]">{page.updated}</p><div className="mt-12 divide-y divide-white/10 border-y border-white/10">{page.sections.map(([title, paragraphs]) => <section key={title} className="grid gap-4 py-7 md:grid-cols-[220px_1fr] md:gap-10"><h2 className="text-sm font-semibold text-white">{title}</h2><div className="space-y-4">{paragraphs.map((paragraph) => <p key={paragraph} className="text-sm leading-7 text-[#98A5AF]">{paragraph}</p>)}</div></section>)}</div><div className="mt-10 flex flex-wrap items-center gap-x-5 gap-y-3 text-sm"><Link href={localePath(locale, otherPath)} className="font-medium text-[#8FDCCD] hover:text-white">{page.other}</Link><a href="mailto:info@n3uralia.com" className="font-medium text-[#8FDCCD] hover:text-white">info@n3uralia.com</a></div></div></article>
    </main>
  )
}
