"use client"

import Link from "next/link"
import { useParams } from "next/navigation"
import { FormEvent, useEffect, useState } from "react"
import { ArrowLeft, Bot, CheckCircle2, Clock3, Loader2, Play, Save, ShieldCheck, Sparkles, Zap } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"

type Policy={case_id:string;enabled:boolean;auto_remind:boolean;auto_raise_priority:boolean;remind_before_hours:number;escalate_before_hours:number;cooldown_hours:number;updated_at:string|null}
type AutomationPayload={currentUserRole:"owner"|"editor"|"viewer";policy:Policy;actions:Array<{id:string;action_type:string;reason:string;created_at:string}>}
type SuggestedAction={action:"remind_reviewers"|"extend_deadline"|"raise_priority"|"open_governance"|"investigate"|"none";rationale:string;confidence:number}
type CopilotReply={answer:string;observations:string[];risks:string[];missing:string[];suggested_actions:SuggestedAction[];model:string;estimatedCostUsd:number}

const ACTION_LABEL:Record<SuggestedAction["action"],string>={remind_reviewers:"Recordar revisores",extend_deadline:"Extender deadline +2 días",raise_priority:"Elevar prioridad",open_governance:"Abrir gobernanza",investigate:"Investigar más",none:"Sin acción"}

export default function CaseControlPage(){
 const {id}=useParams<{id:string}>();const [automation,setAutomation]=useState<AutomationPayload|null>(null);const [question,setQuestion]=useState("¿Qué debería atender primero en este caso?");const [reply,setReply]=useState<CopilotReply|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [saved,setSaved]=useState(false)
 const load=async()=>{setLoading(true);setError(null);try{const r=await fetch(`/api/cases/automation?caseId=${encodeURIComponent(id)}`,{cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"No pudimos cargar el control del caso.");setAutomation(p)}catch(c){setError(c instanceof Error?c.message:"No pudimos cargar el control del caso.")}finally{setLoading(false)}}
 useEffect(()=>{if(id)void load()},[id])
 const patchPolicy=(patch:Partial<Policy>)=>setAutomation(cur=>cur?{...cur,policy:{...cur.policy,...patch}}:cur)
 const savePolicy=async()=>{if(!automation)return;setBusy(true);setSaved(false);setError(null);try{const p=automation.policy;const r=await fetch("/api/cases/automation",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({caseId:id,enabled:p.enabled,autoRemind:p.auto_remind,autoRaisePriority:p.auto_raise_priority,remindBeforeHours:p.remind_before_hours,escalateBeforeHours:p.escalate_before_hours,cooldownHours:p.cooldown_hours})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||"No pudimos guardar la automatización.");setAutomation(cur=>cur?{...cur,policy:body.policy}:cur);setSaved(true)}catch(c){setError(c instanceof Error?c.message:"No pudimos guardar la automatización.")}finally{setBusy(false)}}
 const ask=async(e:FormEvent)=>{e.preventDefault();if(question.trim().length<2)return;setBusy(true);setError(null);try{const r=await fetch("/api/cases/copilot",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({caseId:id,question})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"El Copilot no pudo responder.");setReply(p)}catch(c){setError(c instanceof Error?c.message:"El Copilot no pudo responder.")}finally{setBusy(false)}}
 const execute=async(action:SuggestedAction["action"])=>{if(action==="open_governance"){window.location.href=`/casos/${id}/revision`;return}if(action==="investigate"){window.location.href="/investigar";return}if(action==="none")return;const confirmed=window.confirm(`Confirmar: ${ACTION_LABEL[action]}. Esta acción quedará registrada.`);if(!confirmed)return;setBusy(true);setError(null);try{const r=await fetch("/api/cases/interventions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({caseId:id,action,days:2})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"No pudimos ejecutar la intervención.");await load()}catch(c){setError(c instanceof Error?c.message:"No pudimos ejecutar la intervención.")}finally{setBusy(false)}}
 if(loading)return <div className="mx-auto max-w-6xl px-4 py-14 text-sm text-muted-foreground"><Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>Cargando control…</div>
 if(!automation)return <div className="mx-auto max-w-6xl px-4 py-14 text-destructive">{error}</div>
 const owner=automation.currentUserRole==="owner"
 return <div className="mx-auto flex w-full max-w-6xl flex-col gap-7 px-4 py-10 sm:px-6 lg:py-14">
  <div className="flex flex-wrap items-center justify-between gap-3"><Button asChild variant="ghost" size="sm"><Link href={`/casos/${id}`}><ArrowLeft className="mr-2 h-4 w-4"/>Volver al caso</Link></Button><div className="flex gap-2"><Badge variant="outline"><Zap className="mr-1.5 h-3.5 w-3.5"/>Automation</Badge><Badge variant="outline"><Bot className="mr-1.5 h-3.5 w-3.5"/>Decision Copilot</Badge></div></div>
  <header><Badge variant="secondary">Phase 21 + 22</Badge><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Automatiza el seguimiento. Mantén humana la decisión.</h1><p className="mt-3 max-w-3xl text-muted-foreground">El sistema puede recordar y escalar según reglas explícitas. El Copilot interpreta evidencia y propone intervenciones, pero nunca aprueba ni cierra un caso por sí solo.</p></header>
  {error&&<div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{error}</div>}
  <section className="grid gap-6 lg:grid-cols-2">
   <Card><CardHeader><CardTitle className="flex items-center gap-2"><Zap className="h-5 w-5"/>Escalamiento automático</CardTitle><CardDescription>Reglas deterministas ejecutadas cada hora. Sólo el responsable puede modificarlas.</CardDescription></CardHeader><CardContent className="space-y-5">
    <Toggle label="Automatización activa" description="Habilita el barrido horario para este caso." checked={automation.policy.enabled} disabled={!owner} onChange={v=>patchPolicy({enabled:v})}/>
    <Toggle label="Recordar revisores" description="Envía recordatorios cuando el deadline entra en la ventana configurada." checked={automation.policy.auto_remind} disabled={!owner} onChange={v=>patchPolicy({auto_remind:v})}/>
    <Toggle label="Elevar prioridad automáticamente" description="Puede cambiar la prioridad a alta dentro de la ventana crítica; nunca cambia la decisión." checked={automation.policy.auto_raise_priority} disabled={!owner} onChange={v=>patchPolicy({auto_raise_priority:v})}/>
    <div className="grid gap-3 sm:grid-cols-3"><NumberField label="Recordar antes (h)" value={automation.policy.remind_before_hours} disabled={!owner} onChange={v=>patchPolicy({remind_before_hours:v})}/><NumberField label="Escalar antes (h)" value={automation.policy.escalate_before_hours} disabled={!owner} onChange={v=>patchPolicy({escalate_before_hours:v})}/><NumberField label="Cooldown (h)" value={automation.policy.cooldown_hours} disabled={!owner} onChange={v=>patchPolicy({cooldown_hours:v})}/></div>
    {owner&&<Button onClick={()=>void savePolicy()} disabled={busy}>{busy?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:saved?<CheckCircle2 className="mr-2 h-4 w-4"/>:<Save className="mr-2 h-4 w-4"/>}{saved?"Guardado":"Guardar política"}</Button>}
    <div className="rounded-xl border border-border bg-secondary/20 p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">Límites de seguridad</p><p className="mt-2 text-sm leading-6 text-muted-foreground">No aprueba, no cierra casos, no reasigna revisores y no extiende deadlines automáticamente. Esas acciones siguen requiriendo intervención humana.</p></div>
   </CardContent></Card>
   <Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5"/>Decision Copilot</CardTitle><CardDescription>Consulta el expediente autorizado. La respuesta se registra con modelo, costo estimado y acciones sugeridas.</CardDescription></CardHeader><CardContent>
    <form onSubmit={ask} className="space-y-3"><textarea value={question} onChange={e=>setQuestion(e.target.value)} rows={4} maxLength={1500} className="w-full rounded-xl border border-input bg-background p-3 text-sm" placeholder="¿Qué falta antes de decidir?"/><Button disabled={busy||question.trim().length<2}>{busy?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Play className="mr-2 h-4 w-4"/>}Analizar caso</Button></form>
    {reply&&<div className="mt-5 space-y-4"><div className="rounded-xl border bg-secondary/20 p-4"><p className="text-sm leading-6">{reply.answer}</p><p className="mt-3 text-xs text-muted-foreground">Modelo: {reply.model} · costo estimado: US${reply.estimatedCostUsd.toFixed(6)}</p></div><List title="Observaciones" items={reply.observations}/><List title="Riesgos" items={reply.risks}/><List title="Qué falta" items={reply.missing}/>{reply.suggested_actions.length>0&&<div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">Acciones sugeridas</p><div className="space-y-2">{reply.suggested_actions.map((a,i)=><div key={`${a.action}-${i}`} className="rounded-xl border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-medium">{ACTION_LABEL[a.action]}</p><p className="mt-1 text-xs text-muted-foreground">{a.rationale} · {Math.round(a.confidence*100)}% confianza</p></div>{a.action!=="none"&&<Button size="sm" variant="outline" onClick={()=>void execute(a.action)} disabled={busy}>Confirmar acción</Button>}</div></div>)}</div></div>}</div>}
   </CardContent></Card>
  </section>
  <Card><CardHeader><CardTitle>Actividad automática reciente</CardTitle><CardDescription>Registro visible de recordatorios y escalaciones ejecutadas por reglas.</CardDescription></CardHeader><CardContent>{automation.actions.length===0?<div className="rounded-xl border border-dashed p-7 text-center text-sm text-muted-foreground">Todavía no hay acciones automáticas en este caso.</div>:<div className="space-y-2">{automation.actions.map(a=><div key={a.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div><p className="text-sm font-medium">{a.action_type==="reminder"?"Recordatorio enviado":"Prioridad elevada"}</p><p className="text-xs text-muted-foreground">{a.reason}</p></div><span className="text-xs text-muted-foreground">{new Intl.DateTimeFormat("es-CL",{dateStyle:"short",timeStyle:"short"}).format(new Date(a.created_at))}</span></div>)}</div>}</CardContent></Card>
 </div>
}

function Toggle({label,description,checked,disabled,onChange}:{label:string;description:string;checked:boolean;disabled:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-start justify-between gap-4 rounded-xl border p-4"><span><span className="block text-sm font-medium">{label}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{description}</span></span><input type="checkbox" className="mt-1 h-5 w-5" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/></label>}
function NumberField({label,value,disabled,onChange}:{label:string;value:number;disabled:boolean;onChange:(v:number)=>void}){return <label className="text-xs text-muted-foreground">{label}<Input className="mt-2" type="number" min={1} max={168} value={value} disabled={disabled} onChange={e=>onChange(Math.max(1,Math.min(168,Number(e.target.value)||1)))}/></label>}
function List({title,items}:{title:string;items:string[]}){if(!items.length)return null;return <div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">{title}</p><div className="space-y-2">{items.map((item,i)=><p key={i} className="rounded-lg border border-border px-3 py-2 text-sm leading-5">{item}</p>)}</div></div>}
