import type { Marca } from '@/types/marca'

export const API_PORTAL_MARCAS: Marca[] = [
  {
    id: '1',
    nombre: 'VISUAL COMPARE',
    solicitante: 'Visual Compare Ltd',
    numeroRegistro: '4020230615001',
    niza: ['42', '35'],
    viena: ['26.03.01'],
    estado: 'Registrada',
    fecha: '2023-06-15',
    pais: 'CL',
    descripcion: 'Plataforma de comparacion visual de logos y marcas',
  },
  {
    id: '2',
    nombre: 'COMPARE PRO',
    solicitante: 'Software Innovations Inc',
    numeroRegistro: '4020230322002',
    niza: ['42', '09'],
    viena: ['26.01.01'],
    estado: 'Registrada',
    fecha: '2023-03-22',
    pais: 'US',
    descripcion: 'Software profesional de comparacion',
  },
  {
    id: '3',
    nombre: 'LOGO MATCH',
    solicitante: 'Design Studio Chile',
    numeroRegistro: '4020240110003',
    niza: ['41', '42'],
    viena: ['26.03.01', '26.03.15'],
    estado: 'Pendiente',
    fecha: '2024-01-10',
    pais: 'CL',
    descripcion: 'Sistema de emparejamiento de logos',
  },
  {
    id: '4',
    nombre: 'MARCA SHIELD',
    solicitante: 'IP Protection Services',
    numeroRegistro: '4020221105004',
    niza: ['45'],
    viena: ['26.04.01'],
    estado: 'Registrada',
    fecha: '2022-11-05',
    pais: 'MX',
    descripcion: 'Proteccion de marcas registradas',
  },
  {
    id: '5',
    nombre: 'VISUAL TECH',
    solicitante: 'Technology Innovations',
    numeroRegistro: '4020230820005',
    niza: ['42', '35', '09'],
    viena: ['26.03.01'],
    estado: 'Registrada',
    fecha: '2023-08-20',
    pais: 'AR',
    descripcion: 'Tecnologia visual avanzada',
  },
  // Marcas de bebidas — para validar conflictos en sector alimentacion/bebidas
  {
    id: '6',
    nombre: 'TORO',
    solicitante: 'Bebidas del Pacifico SpA',
    numeroRegistro: '4020190415006',
    niza: ['32', '33'],
    viena: ['03.02.02', '26.03.01', '27.01.01', '29.01.02'],
    estado: 'Registrada',
    fecha: '2019-04-15',
    pais: 'CL',
    descripcion: 'Bebidas alcoholicas y no alcoholicas con imagen de toro',
  },
  {
    id: '7',
    nombre: 'TORITO ROJO',
    solicitante: 'Energy Drinks Chile Ltda',
    numeroRegistro: '4020210830007',
    niza: ['32'],
    viena: ['03.02.02', '26.05.01', '27.01.01', '29.01.02'],
    estado: 'Registrada',
    fecha: '2021-08-30',
    pais: 'CL',
    descripcion: 'Bebida energetica con imagen de toro y hexagono',
  },
  {
    id: '8',
    nombre: 'EL TORO ENERGY',
    solicitante: 'Global Beverages SA',
    numeroRegistro: '4020200612008',
    niza: ['32', '35'],
    viena: ['03.01.01', '26.03.01', '27.01.01'],
    estado: 'Registrada',
    fecha: '2020-06-12',
    pais: 'MX',
    descripcion: 'Bebida energetica con toro y circulo',
  },
  {
    id: '9',
    nombre: 'BULL POWER',
    solicitante: 'Power Drinks International',
    numeroRegistro: '4020221020009',
    niza: ['32'],
    viena: ['03.02.02', '26.04.01', '27.01.01'],
    estado: 'Registrada',
    fecha: '2022-10-20',
    pais: 'US',
    descripcion: 'Bebida energizante con toro y triangulo',
  },
  {
    id: '10',
    nombre: 'BEBIDAS CAMPO',
    solicitante: 'Campo Frutas Chile',
    numeroRegistro: '4020180305010',
    niza: ['29', '30', '32'],
    viena: ['04.03.01', '04.05.01', '29.01.03'],
    estado: 'Registrada',
    fecha: '2018-03-05',
    pais: 'CL',
    descripcion: 'Jugos y bebidas naturales de frutas',
  },
  {
    id: '11',
    nombre: 'TORO ROJO',
    solicitante: 'Red Bull GmbH (representante CL)',
    numeroRegistro: '4019990101011',
    niza: ['32'],
    viena: ['03.02.02', '26.03.01', '29.01.02'],
    estado: 'Registrada',
    fecha: '1999-01-01',
    pais: 'AT',
    descripcion: 'Bebida energetica con toro rojo — marca historica',
  },
]

// Clasificación Niza — NCL 13a edición (WIPO 2026) — 45 clases completas
export const API_PORTAL_NIZA = [
  { codigo: '01', titulo: 'Productos químicos para industria, ciencia y fotografía' },
  { codigo: '02', titulo: 'Pinturas, barnices, lacas y productos anticorrosivos' },
  { codigo: '03', titulo: 'Cosméticos, productos de limpieza y perfumería' },
  { codigo: '04', titulo: 'Aceites, grasas industriales y combustibles' },
  { codigo: '05', titulo: 'Productos farmacéuticos y veterinarios' },
  { codigo: '06', titulo: 'Metales comunes y sus aleaciones; materiales de construcción metálicos' },
  { codigo: '07', titulo: 'Máquinas, herramientas mecánicas y motores' },
  { codigo: '08', titulo: 'Herramientas e instrumentos manuales' },
  { codigo: '09', titulo: 'Aparatos científicos, tecnológicos, software y dispositivos electrónicos' },
  { codigo: '10', titulo: 'Aparatos e instrumentos médicos y odontológicos' },
  { codigo: '11', titulo: 'Aparatos de alumbrado, calefacción, refrigeración y cocción' },
  { codigo: '12', titulo: 'Vehículos y aparatos de locomoción terrestre, aérea o acuática' },
  { codigo: '13', titulo: 'Armas de fuego, municiones y artículos de pirotecnia' },
  { codigo: '14', titulo: 'Metales preciosos, joyería, relojería y piedras preciosas' },
  { codigo: '15', titulo: 'Instrumentos musicales y accesorios' },
  { codigo: '16', titulo: 'Papel, cartón, material impreso, artículos de oficina y papelería' },
  { codigo: '17', titulo: 'Caucho, gutapercha, materiales plásticos en bruto y aislantes' },
  { codigo: '18', titulo: 'Cuero, artículos de viaje, bolsos y marroquinería' },
  { codigo: '19', titulo: 'Materiales de construcción no metálicos; tuberías rígidas' },
  { codigo: '20', titulo: 'Muebles, espejos, marcos y recipientes de madera o plástico' },
  { codigo: '21', titulo: 'Utensilios y recipientes domésticos; artículos de vidrio' },
  { codigo: '22', titulo: 'Cuerdas, redes, tiendas, toldos, velas y sacos' },
  { codigo: '23', titulo: 'Hilos para uso textil' },
  { codigo: '24', titulo: 'Tejidos y telas; ropa de cama y de mesa' },
  { codigo: '25', titulo: 'Prendas de vestir, calzado y artículos de sombrerería' },
  { codigo: '26', titulo: 'Encajes, bordados, cintas, botones y artículos de mercería' },
  { codigo: '27', titulo: 'Alfombras, tapices, felpudos y revestimientos de suelos' },
  { codigo: '28', titulo: 'Juegos, juguetes, artículos deportivos y de gimnasia' },
  { codigo: '29', titulo: 'Carne, pescado, aves, productos lácteos y conservas' },
  { codigo: '30', titulo: 'Café, té, cacao, cereales, pan, confitería y condimentos' },
  { codigo: '31', titulo: 'Productos agrícolas, hortícolas y forestales en bruto; animales vivos' },
  { codigo: '32', titulo: 'Cervezas, aguas minerales, jugos y bebidas no alcohólicas' },
  { codigo: '33', titulo: 'Bebidas alcohólicas (excepto cervezas); vinos y licores' },
  { codigo: '34', titulo: 'Tabaco, artículos para fumadores y productos de vapeo' },
  { codigo: '35', titulo: 'Publicidad, gestión comercial, administración de empresas y negocios' },
  { codigo: '36', titulo: 'Seguros, servicios financieros, monetarios e inmobiliarios' },
  { codigo: '37', titulo: 'Servicios de construcción, reparación e instalación' },
  { codigo: '38', titulo: 'Servicios de telecomunicaciones y comunicaciones' },
  { codigo: '39', titulo: 'Transporte, embalaje, almacenamiento y distribución' },
  { codigo: '40', titulo: 'Tratamiento de materiales y procesamiento de alimentos' },
  { codigo: '41', titulo: 'Educación, entretenimiento, actividades deportivas y culturales' },
  { codigo: '42', titulo: 'Servicios científicos, tecnológicos, investigación y diseño de software' },
  { codigo: '43', titulo: 'Servicios de restauración, alimentos, hospedaje temporal' },
  { codigo: '44', titulo: 'Servicios médicos, veterinarios, de higiene y de estética' },
  { codigo: '45', titulo: 'Servicios jurídicos, de seguridad personal y sociales' },
]

// Clasificación Viena — VCL 10a edición (WIPO 2026) — códigos con descripciones reales
export const API_PORTAL_VIENA = [
  // Cat. 02 — Seres humanos
  { codigo: '02.01.01', titulo: 'Hombres (figura completa)' },
  { codigo: '02.01.04', titulo: 'Figuras humanas estilizadas o abstractas' },
  { codigo: '02.03.01', titulo: 'Niños y bebés' },
  { codigo: '02.05.01', titulo: 'Cabezas o rostros humanos' },
  { codigo: '02.05.05', titulo: 'Ojos humanos' },
  { codigo: '02.09.01', titulo: 'Siluetas humanas' },
  // Cat. 03 — Animales
  { codigo: '03.01.01', titulo: 'Leones' },
  { codigo: '03.01.04', titulo: 'Tigres y leopardos' },
  { codigo: '03.02.01', titulo: 'Caballos' },
  { codigo: '03.04.01', titulo: 'Perros' },
  { codigo: '03.07.01', titulo: 'Aves en general' },
  { codigo: '03.07.03', titulo: 'Águilas y cóndores' },
  { codigo: '03.07.12', titulo: 'Colibríes y aves pequeñas' },
  { codigo: '03.13.01', titulo: 'Peces' },
  // Cat. 04 — Elementos de la naturaleza y plantas
  { codigo: '04.01.01', titulo: 'Árboles (completos)' },
  { codigo: '04.03.01', titulo: 'Flores' },
  { codigo: '04.05.01', titulo: 'Hojas y ramas' },
  { codigo: '04.07.01', titulo: 'Frutas y verduras' },
  // Cat. 05 — Paisajes
  { codigo: '05.01.01', titulo: 'Paisajes y escenas al aire libre' },
  { codigo: '05.03.01', titulo: 'Agua, ríos, mares y cascadas' },
  { codigo: '05.05.01', titulo: 'Montañas y cordilleras' },
  // Cat. 06 — Escenas y construcciones
  { codigo: '06.01.01', titulo: 'Paisajes urbanos y edificios' },
  // Cat. 07 — Construcciones y estructuras
  { codigo: '07.01.01', titulo: 'Edificios y casas' },
  { codigo: '07.03.01', titulo: 'Puentes y arcos estructurales' },
  // Cat. 24 — Signos y símbolos
  { codigo: '24.01.01', titulo: 'Puntos y comas' },
  { codigo: '24.09.01', titulo: 'Flechas y signos de dirección' },
  { codigo: '24.15.01', titulo: 'Signos de interrogación y exclamación' },
  // Cat. 26 — Figuras geométricas (la más importante para logos)
  { codigo: '26.01.01', titulo: 'Líneas horizontales o verticales' },
  { codigo: '26.01.05', titulo: 'Líneas diagonales' },
  { codigo: '26.01.06', titulo: 'Líneas que forman ángulos o chevrones' },
  { codigo: '26.02.01', titulo: 'Cuadrados' },
  { codigo: '26.02.05', titulo: 'Rectángulos' },
  { codigo: '26.02.08', titulo: 'Rombos' },
  { codigo: '26.03.01', titulo: 'Círculos simples' },
  { codigo: '26.03.07', titulo: 'Círculos concéntricos o que forman figuras' },
  { codigo: '26.03.10', titulo: 'Óvalos y elipses' },
  { codigo: '26.04.01', titulo: 'Triángulos apuntando hacia arriba' },
  { codigo: '26.04.04', titulo: 'Triángulos apuntando hacia abajo' },
  { codigo: '26.05.01', titulo: 'Pentágonos, hexágonos y polígonos' },
  { codigo: '26.07.04', titulo: 'Estrellas de 5 puntas' },
  { codigo: '26.07.06', titulo: 'Estrellas de 6 o más puntas' },
  { codigo: '26.11.01', titulo: 'Figuras geométricas tridimensionales (cubos, esferas)' },
  { codigo: '26.13.01', titulo: 'Figuras geométricas que contienen letras o texto' },
  // Cat. 27 — Letras y texto
  { codigo: '27.01.01', titulo: 'Letras latinas mayúsculas (tipografía estándar)' },
  { codigo: '27.01.04', titulo: 'Letras latinas minúsculas (tipografía estándar)' },
  { codigo: '27.03.01', titulo: 'Letras en tipografía decorativa o estilizada' },
  { codigo: '27.05.01', titulo: 'Una sola letra como elemento gráfico principal' },
  { codigo: '27.05.24', titulo: 'Texto dispuesto en arco o curva' },
  { codigo: '27.07.01', titulo: 'Cifras y números arábigos' },
  // Cat. 28 — Colores y fondos
  { codigo: '28.01.01', titulo: 'Fondo de color uniforme o sólido' },
  { codigo: '28.01.08', titulo: 'Fondo degradado o con gradiente' },
  // Cat. 29 — Colores dominantes
  { codigo: '29.01.01', titulo: 'Azul como color dominante' },
  { codigo: '29.01.02', titulo: 'Rojo como color dominante' },
  { codigo: '29.01.03', titulo: 'Verde como color dominante' },
  { codigo: '29.01.04', titulo: 'Amarillo o dorado como color dominante' },
  { codigo: '29.01.05', titulo: 'Negro y blanco (sin otros colores)' },
  { codigo: '29.01.06', titulo: 'Naranja como color dominante' },
  { codigo: '29.01.07', titulo: 'Violeta o púrpura como color dominante' },
]

export function findMarcaById(id: string) {
  return API_PORTAL_MARCAS.find((marca) => marca.id === id) ?? null
}
