export type PublicLocale = "es" | "en"

export function localePath(locale: PublicLocale, path = "/") {
  if (path === "/") return `/${locale}`
  const normalized = path.startsWith("/") ? path : `/${path}`
  return `/${locale}${normalized}`
}

export const landingCopy = {
  es: {
    navAria: "Navegación principal",
    brandAria: "VIDENTIA, inicio",
    brandTagline: "INTELIGENCIA Y PROTECCIÓN DE MARCAS",
    nav: { search: "Buscar", register: "Registrar", watch: "Vigilar", manage: "Gestionar", pricing: "Precios", resources: "Recursos", login: "Iniciar sesión", cta: "Buscar una marca" },
    hero: { kicker: "FUENTES OFICIALES · EVIDENCIA TRAZABLE", line1: "Protege tu marca", line2: "desde antes de", line3: "registrarla.", lead: "Investiga antecedentes, registra, vigila y administra tus marcas desde un solo lugar.", searchLabel: "Buscar una marca, nombre o logo", searchPlaceholder: "Buscar una marca, nombre o logo", searchButton: "Buscar", imageAlt: "Dos personas comparan marcas con grandes lupas sobre geometría Bauhaus de VIDENTIA" },
    trust: [["Revisión inicial", "Valida antecedentes antes de invertir más tiempo."], ["Fuentes oficiales", "Trabaja con evidencia identificable y contexto verificable."], ["Evidencia trazable", "Cada señal conserva fuente, fecha y explicación."], ["Alertas inteligentes", "Prioriza cambios que realmente requieren revisión."]],
    process: { eyebrow: "02. CÓMO FUNCIONA", title1: "Un proceso simple,", title2: "inteligente y trazable.", body: "Desde una búsqueda inicial hasta la protección continua, cada etapa conserva contexto y evidencia.", steps: [["Busca", "Encuentra la marca o nombre que quieres investigar."], ["Analiza", "Recopila antecedentes desde fuentes identificables."], ["Evalúa", "Organiza similitud, señales y evidencia para revisión."], ["Protege", "Conecta registro, vigilancia y administración continua."]] },
    capabilities: { eyebrow: "03. CAPACIDADES PRINCIPALES", title1: "Todo lo que necesitas", title2: "para proteger tu marca.", items: [["Búsqueda profunda", "Reduce ruido y prioriza antecedentes denominativos, fonéticos y visuales que merecen revisión."], ["Vigilancia continua", "Sigue nuevas solicitudes y cambios relevantes sin repetir manualmente la investigación."], ["Gestión centralizada", "Administra marcas, solicitudes, documentos y responsables desde un mismo sistema."], ["Reportes con evidencia", "Convierte señales y fuentes identificables en reportes claros, trazables y revisables."]], ctaBody: "Investiga hoy. Mantén el control después.", cta: "Acceso empresarial" },
    audience: { eyebrow: "04. PARA QUIÉN ES", title1: "Diseñado para equipos", title2: "que construyen marcas.", body: "Una misma infraestructura para investigar, decidir, gestionar y vigilar durante todo el ciclo de vida de una marca.", items: ["Emprendedores", "Estudios jurídicos", "Empresas", "Agencias", "Equipos legales"] },
    protection: { eyebrow: "05. PROTECCIÓN CONTINUA", title: "Portfolio + Watch + Deadlines.", body: "El valor durable aparece después de la búsqueda: qué posees, qué cambió, qué requiere atención y cuál es el próximo plazo.", items: [["Portfolio", "Una marca persistente, un historial y un lugar para entender qué posees."], ["Watch", "Señales priorizadas para saber qué cambió y qué requiere revisión."], ["Deadlines", "Plazos visibles y accionables conectados con cada solicitud y evento."]] },
    final: { eyebrow: "06. EMPIEZA HOY", title1: "Empieza a proteger", title2: "tu marca hoy.", body: "Haz una vista preliminar antes de solicitar acceso empresarial.", primary: "Buscar una marca", secondary: "Acceso empresarial" },
    footer: { body: "Investigación, evidencia, seguimiento y administración de marcas desde un mismo sistema.", platform: "Plataforma", search: "Buscar", process: "Proceso", watch: "Vigilar", manage: "Gestionar", resources: "Recursos", docs: "Documentación", contact: "Contacto", login: "Iniciar sesión", legal: "Legal", privacy: "Privacidad", terms: "Términos", disclaimer: "VIDENTIA apoya investigación y revisión de evidencia. No reemplaza la evaluación jurídica profesional ni las fuentes oficiales.", credit: "Un desarrollo de N3uralia" },
    language: { current: "ES", switchLabel: "English", switchLocale: "en" as const },
  },
  en: {
    navAria: "Primary navigation",
    brandAria: "VIDENTIA, home",
    brandTagline: "TRADEMARK INTELLIGENCE AND PROTECTION",
    nav: { search: "Search", register: "Register", watch: "Watch", manage: "Manage", pricing: "Pricing", resources: "Resources", login: "Sign in", cta: "Search a trademark" },
    hero: { kicker: "OFFICIAL SOURCES · TRACEABLE EVIDENCE", line1: "Protect your trademark", line2: "before you", line3: "register it.", lead: "Research prior rights, register, monitor and manage your trademarks from one place.", searchLabel: "Search a trademark, name or logo", searchPlaceholder: "Search a trademark, name or logo", searchButton: "Search", imageAlt: "Two people compare trademarks through large magnifying glasses over VIDENTIA Bauhaus geometry" },
    trust: [["Initial review", "Check prior rights before investing more time."], ["Official sources", "Work with identifiable evidence and verifiable context."], ["Traceable evidence", "Every signal keeps its source, date and explanation."], ["Smart alerts", "Prioritize changes that genuinely require review."]],
    process: { eyebrow: "02. HOW IT WORKS", title1: "A simple process,", title2: "intelligent and traceable.", body: "From the first search to continuous protection, every stage preserves context and evidence.", steps: [["Search", "Find the trademark or name you want to investigate."], ["Analyze", "Collect prior rights from identifiable sources."], ["Review", "Organize similarity, signals and evidence for review."], ["Protect", "Connect registration, monitoring and ongoing management."]] },
    capabilities: { eyebrow: "03. CORE CAPABILITIES", title1: "Everything you need", title2: "to protect your trademark.", items: [["Deep search", "Reduce noise and prioritize word, phonetic and visual prior rights that deserve review."], ["Continuous monitoring", "Track new applications and relevant changes without repeating the investigation manually."], ["Centralized management", "Manage trademarks, applications, documents and owners from one system."], ["Evidence-based reports", "Turn signals and identifiable sources into clear, traceable and reviewable reports."]], ctaBody: "Investigate today. Stay in control afterwards.", cta: "Enterprise access" },
    audience: { eyebrow: "04. WHO IT IS FOR", title1: "Built for teams", title2: "that build brands.", body: "One infrastructure to research, decide, manage and monitor throughout the trademark lifecycle.", items: ["Founders", "Law firms", "Companies", "Agencies", "Legal teams"] },
    protection: { eyebrow: "05. CONTINUOUS PROTECTION", title: "Portfolio + Watch + Deadlines.", body: "The durable value starts after the search: what you own, what changed, what needs attention and what deadline comes next.", items: [["Portfolio", "A persistent trademark record, its history and one place to understand what you own."], ["Watch", "Prioritized signals showing what changed and what deserves review."], ["Deadlines", "Visible, actionable deadlines connected to each application and event."]] },
    final: { eyebrow: "06. GET STARTED", title1: "Start protecting", title2: "your trademark today.", body: "Run a preliminary view before requesting enterprise access.", primary: "Search a trademark", secondary: "Enterprise access" },
    footer: { body: "Trademark research, evidence, monitoring and management in one system.", platform: "Platform", search: "Search", process: "Process", watch: "Watch", manage: "Manage", resources: "Resources", docs: "Documentation", contact: "Contact", login: "Sign in", legal: "Legal", privacy: "Privacy", terms: "Terms", disclaimer: "VIDENTIA supports research and evidence review. It does not replace professional legal assessment or official sources.", credit: "Developed by N3uralia" },
    language: { current: "EN", switchLabel: "Español", switchLocale: "es" as const },
  },
} as const
