"use client"

import Link from "next/link"
import { FormEvent, useEffect, useMemo, useState } from "react"
import { useParams } from "next/navigation"
import { ArrowLeft, CheckCircle2, Clock3, Loader2, ShieldCheck, XCircle } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"

type Member={user_id:string;email:string;display_name:string;role:"owner"|"editor"|"viewer";is_owner:boolean}
type Review={id:string;requested_by:string;reviewer_id:string;status:"pending"|"approved"|"changes_requested"|"cancelled";message:string|null;response_note:string|null;created_at:string;responded_at:string|null;governance_round_id:string|null;deadline_at:string|null}
type Governance={required_approvals:number;review_deadline_days:number;block_on_changes:boolean;current_round_id:string|null;round_deadline_at:string|null}
type GovernanceStatus={state:"ready_for_approval"|"waiting"|"blocked"|"approved"|"overdue";required_approvals:number;approved_count:number;pending_count:number;changes_count:number;total_reviewers:number;deadline_at:string|null;waiting_on:string[]}
type Payload={currentUserId:string;currentUserRole:"owner"|"editor"|"viewer";reviews:Review[];members:Member[];governance:Governance|null;governanceStatus:GovernanceStatus|null}

const STATE_LABEL={ready_for_approval:"Lista para aprobación",waiting:"Esperando revisores",blocked:"Bloqueada",approved:"Aprobada",overdue:"Vencida"} as const
const REVIEW_LABEL={pending:"Pendiente",approved:"Aprobado",changes_requested:"Requiere cambios",cancelled:"Cancelado"} as const
const fmt=(v:string)=>new Intl.DateTimeFormat("es-CL",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))

export default function CaseReviewPage(){
 const {id}=useParams<{id:string}>();const [data,setData]=useState<Payload|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [selected,setSelected]=useState<string[]>([]);const [required,setRequired]=useState(1);const [days,setDays]=useState(3);const [message,setMessage]=useState("");const [notes,setNotes]=useState<Record<string,string>>({})
 const load=async()=>{setLoading(true);setError(null);try{const r=await fetch(`/api/cases/reviews?caseId=${encodeURIComponent(id)}`,{cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"No pudimos cargar revisiones.");setData(p);setRequired(p.governance?.required_approvals??1);setDays(p.governance?.review_deadline_days??3)}catch(c){setError(c instanceof Error?c.message:"No pudimos cargar revisiones.")}finally{setLoading(false)}}
 useEffect(()=>{if(id)void load()},[id]);const memberMap=useMemo(()=>new Map((data?.members??[]).map(m=>[m.user_id,m])),[data]);const canRequest=data?.currentUserRole==="owner"||data?.currentUserRole==="editor";const canPolicy=data?.currentUserRole==="owner";const eligible=data?.members.filter(m=>m.user_id!==data.currentUserId)??[]
 const start=async(e:FormEvent)=>{e.preventDefault();if(!selected.length)return;setBusy(true);setError(null);try{const r=await fetch("/api/cases/reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"round",caseId:id,reviewerIds:selected,message,requiredApprovals:required,deadlineDays:days,blockOnChanges:true})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"No pudimos iniciar la aprobación.");setSelected([]);setMessage("");await load()}catch(c){setError(c instanceof Error?c.message:"No pudimos iniciar la aprobación.")}finally{setBusy(false)}}
 const act=async(review:Review,action:"approved"|"changes_requested"|"cancelled")=>{setBusy(true);const r=await fetch("/api/cases/reviews",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:review.id,action,note:notes[review.id]||null})});if(!r.ok){const p=await r.json().catch(()=>({}));setError(p.error||"No pudimos actualizar la revisión.")}else await load();setBusy(false)}
 if(loading)return <div className="mx-auto max-w-6xl px-4 py-14 text-sm text-muted-foreground"><Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>Cargando gobernanza…</div>;if(!data)return <div className="mx-auto max-w-6xl px-4 py-14 text-destructive">{error}</div>
 const gs=data.governanceStatus
 return <div className="mx-auto flex w-full max-w-6xl flex-col gap-7 px-4 py-10 sm:px-6 lg:py-14">
  <div className="flex items-center justify-between gap-3"><Button asChild variant="ghost" size="sm"><Link href={`/casos/${id}`}><ArrowLeft className="mr-2 h-4 w-4"/>Volver al caso</Link></Button><Badge variant="outline"><ShieldCheck className="mr-1.5 h-3.5 w-3.5"/>{gs?STATE_LABEL[gs.state]:"Sin política"}</Badge></div>
  <header><Badge variant="secondary">Decision Governance</Badge><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Aprobaciones con reglas claras.</h1><p className="mt-3 max-w-3xl text-muted-foreground">Define cuántas aprobaciones necesita el caso, quién revisa y cuándo vence la ronda. El caso sólo puede cerrarse cuando alcanza el quórum.</p></header>
  {error&&<div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{error}</div>}
  {gs&&<section className="grid gap-3 sm:grid-cols-4"><Metric label="Estado" value={STATE_LABEL[gs.state]}/><Metric label="Aprobaciones" value={`${gs.approved_count}/${gs.required_approvals}`}/><Metric label="Pendientes" value={String(gs.pending_count)}/><Metric label="Deadline" value={gs.deadline_at?fmt(gs.deadline_at):"Sin ronda"}/></section>}
  {canRequest&&<Card><CardHeader><CardTitle>Nueva ronda de aprobación</CardTitle><CardDescription>{canPolicy?"Configura quórum y deadline antes de iniciar.":"Usará la política definida por el responsable."}</CardDescription></CardHeader><CardContent><form onSubmit={start} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2">{canPolicy&&<><label className="text-sm">Aprobaciones requeridas<Input type="number" min={1} max={Math.max(1,eligible.length)} value={required} onChange={e=>setRequired(Number(e.target.value))}/></label><label className="text-sm">Días para revisar<Input type="number" min={1} max={30} value={days} onChange={e=>setDays(Number(e.target.value))}/></label></>}</div><div className="grid gap-2 sm:grid-cols-2">{eligible.map(m=>{const active=selected.includes(m.user_id);return <button type="button" key={m.user_id} onClick={()=>setSelected(cur=>active?cur.filter(x=>x!==m.user_id):[...cur,m.user_id])} className={`rounded-xl border p-3 text-left ${active?"border-foreground bg-secondary":"border-border"}`}><p className="text-sm font-medium">{m.display_name}</p><p className="text-xs text-muted-foreground">{m.email}</p></button>})}</div><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={3} maxLength={1000} className="w-full rounded-xl border border-input bg-background p-3 text-sm" placeholder="Qué decisión deben revisar…"/><Button disabled={busy||selected.length<Math.max(1,required)}>Iniciar ronda con {selected.length} revisor{selected.length===1?"":"es"}</Button></form></CardContent></Card>}
  <Card><CardHeader><CardTitle>Revisiones</CardTitle><CardDescription>Las respuestas individuales alimentan automáticamente el estado de la ronda.</CardDescription></CardHeader><CardContent className="space-y-3">{data.reviews.length===0?<p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Todavía no hay revisiones.</p>:data.reviews.map(r=>{const reviewer=memberMap.get(r.reviewer_id);const isReviewer=r.reviewer_id===data.currentUserId&&r.status==="pending";const canCancel=r.status==="pending"&&(r.requested_by===data.currentUserId||data.currentUserRole==="owner");return <div key={r.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><Badge variant={r.status==="pending"?"secondary":"outline"}>{REVIEW_LABEL[r.status]}</Badge><p className="mt-2 text-sm font-medium">{reviewer?.display_name||"Participante"}</p><p className="text-xs text-muted-foreground">{r.deadline_at?`Vence ${fmt(r.deadline_at)}`:`Solicitada ${fmt(r.created_at)}`}</p>{r.response_note&&<p className="mt-3 rounded-lg bg-secondary/40 p-3 text-sm">{r.response_note}</p>}</div>{r.status==="pending"?<Clock3 className="h-5 w-5 text-muted-foreground"/>:r.status==="approved"?<CheckCircle2 className="h-5 w-5"/>:<XCircle className="h-5 w-5"/>}</div>{isReviewer&&<div className="mt-4 space-y-3 border-t pt-4"><textarea value={notes[r.id]??""} onChange={e=>setNotes(cur=>({...cur,[r.id]:e.target.value}))} rows={2} className="w-full rounded-xl border p-3 text-sm" placeholder="Comentario de revisión…"/><div className="flex gap-2"><Button onClick={()=>void act(r,"approved")} disabled={busy}>Aprobar</Button><Button variant="outline" onClick={()=>void act(r,"changes_requested")} disabled={busy}>Pedir cambios</Button></div></div>}{canCancel&&<Button size="sm" variant="ghost" className="mt-2" onClick={()=>void act(r,"cancelled")}>Cancelar</Button>}</div>})}</CardContent></Card>
 </div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>}
