import { randomUUID } from "node:crypto"
import { NextResponse } from "next/server"
import { createAdminClient } from "@/lib/supabase/admin"
import { extractExif, type ExifData } from "@/lib/image/exif"
import { calculateSha256 } from "@/lib/image/hash"
import { computeEla } from "@/lib/image/ela"
import { extractMetadata } from "@/lib/image/metadata"