import { readFile } from "node:fs/promises"
import { strict as assert } from "node:assert"

const migration = await readFile("supabase/migrations/20260908140000_create_assistant_response_feedback.sql", "utf8")
const indexMigration = await readFile("supabase/migrations/20260908140100_index_assistant_response_feedback_owner.sql", "utf8")
const api = await readFile("app/api/assistant/feedback/route.ts", "utf8")
const assistantRoute = await readFile("app/api/assistant/route.ts", "utf8")
const metrics = await readFile("lib/intelligence/assistant-execution-metrics.ts", "utf8")
const feedback = await readFile("lib/intelligence/assistant-response-feedback.ts", "utf8")
const feedbackUi = await readFile("components/app/assistant-response-feedback.tsx", "utf8")
const launcher = await readFile("components/app/videntia-assistant-launcher.tsx", "utf8")
const lifecycle = await readFile("lib/intelligence/videntia-improvement-lifecycle.ts", "utf8")
const radar = await readFile("lib/intelligence/videntia-improvement-radar.ts", "utf8")

assert.match(migration, /intelligence_assistant_response_feedback/)
assert.match(migration, /foreign key \(execution_metric_id, user_id\)/)
assert.match(migration, /references public\.intelligence_assistant_execution_metrics\(id, user_id\)/)
assert.match(migration, /enable row level security/)
assert.match(migration, /revoke all on table public\.intelligence_assistant_response_feedback from anon, authenticated/)
assert.match(migration, /for all to service_role using \(true\) with check \(true\)/)
assert.doesNotMatch(migration, /\b(note|prompt|message|content)\s+text\b/i)
assert.match(migration, /'resolved','partial','not_resolved'/)
assert.match(migration, /'incorrect','missing_evidence','incomplete','misunderstood','needed_followup','other'/)
assert.match(indexMigration, /\(execution_metric_id, user_id\)/)

assert.match(api, /requireUser\(\)/)
assert.match(api, /executionId: z\.string\(\)\.uuid\(\)/)
assert.match(api, /recordAssistantResponseFeedback\(\{/)
assert.match(api, /userId: auth\.user\.id/)
assert.doesNotMatch(api, /userId:\s*parsed\.data/)
assert.match(api, /PRIVATE_NO_STORE_HEADERS/)

assert.match(feedback, /\.eq\("id", input\.executionMetricId\)/)
assert.match(feedback, /\.eq\("user_id", input\.userId\)/)
assert.match(feedback, /onConflict: "execution_metric_id"/)
assert.match(feedback, /feedbackCoverage/)
assert.match(feedback, /resolvedRate/)
assert.match(feedback, /notResolvedRate/)
assert.doesNotMatch(feedback, /qualityScore|conviction|score\s*:/i)

assert.match(metrics, /\.select\("id"\)\.single\(\)/)
assert.match(metrics, /Promise<string \| null>/)
assert.match(assistantRoute, /const executionMetricId = await recordAssistantExecutionMetric\(metric\)/)
assert.match(assistantRoute, /executionId: executionMetricId/)

assert.match(launcher, /executionId\?: string/)
assert.match(launcher, /typeof payload\.executionId === "string"/)
assert.match(launcher, /<AssistantResponseFeedback executionId=\{message\.executionId\}/)
assert.match(feedbackUi, /¿Resolvió tu consulta\?/)
assert.match(feedbackUi, /value: "resolved", label: "Sí"/)
assert.match(feedbackUi, /value: "partial", label: "Parcial"/)
assert.match(feedbackUi, /value: "not_resolved", label: "No"/)
assert.match(feedbackUi, /Faltó evidencia/)
assert.match(feedbackUi, /Necesité repreguntar/)
assert.match(feedbackUi, /no el texto de la conversación/)

assert.match(lifecycle, /feedbackSampleSize/)
assert.match(lifecycle, /feedbackCoverage/)
assert.match(lifecycle, /qualityDecisionEffect: "none"/)
assert.match(radar, /calidad explícita de la respuesta/)
assert.match(radar, /GitHub, telemetría y operación interna son señales de producto, no evidencia del mercado/)
assert.match(radar, /feedback explícito del Assistant también es una señal de producto y no evidencia de mercado/)

console.log("Assistant response feedback regression PASS: structured private feedback is execution-bound, ownership-scoped, no-text, coverage-aware and separated from evidence conviction.")
