import { readFile } from "node:fs/promises"

function fail(message:string):never{console.error(`Patent prior-art regression FAIL: ${message}`);process.exit(1)}
function requireText(source:string,needle:string,label:string){if(!source.includes(needle))fail(`${label} missing ${needle}`)}

const [builder,epo,route,page,recorder,externalVerification]=await Promise.all([
  readFile("lib/intelligence/patent-prior-art.ts","utf8"),
  readFile("lib/intelligence/epo-ops.ts","utf8"),
  readFile("app/api/patents/prior-art/route.ts","utf8"),
  readFile("app/(app)/patentes/prior-art/page.tsx","utf8"),
  readFile("lib/intelligence/source-change-recorder.ts","utf8"),
  readFile("components/app/patent-external-verification.tsx","utf8"),
])

for(const needle of [
  "extractTechnicalConcepts",
  "shouldFallback",
  "searchPatentsLocal(concept",
  "parsePriorityClaims",
  "pctApplicationDate",
  "familyCandidate",
  "globalFamilyMatches",
  "matchGlobalFamilies",
  "priorityClaimsMatch",
  "priorityNumberVariants",
  "globalFamilyLinkedCandidates",
  "priorityClaimsForGlobal",
  "searchEpoPatentFamiliesForReview(query, priorityClaims, 3)",
  "La recuperación global prioriza números de prioridad observados en los candidatos INAPI",
  "Vínculo EPO por prioridad observada:",
  "Los vínculos INAPI ↔ EPO se declaran sólo cuando una prioridad observada coincide por país, fecha y variante normalizada del número",
  'if (score >= 65) return "close_review"',
  'source: "INAPI Chile"',
  "loadGlobalPatentEvidence",
  "hasEpoOpsCredentials",
  'availability: "credential_required"',
  "intelligence_source_events",
  'source_key", "inapi_open_data"',
  'entity_type", "patent"',
  "observedChangeCount",
  "observedChanges",
  "fieldChanges",
  "changeObservationSince",
  "Los cambios observados comparan snapshots sucesivos del dataset oficial",
  "Los eventos jurídicos EPO se presentan como eventos de fuente",
  "Un resultado vacío no demuestra ausencia de prior art, familia, citas, derechos activos ni eventos jurídicos.",
])requireText(builder,needle,"prior-art builder")

for(const needle of [
  "status_changed",
  "registration_added",
  "applicant_changed",
  "classification_changed",
  "title_changed",
  "before_snapshot",
  "after_snapshot",
  "observed_at",
  "materiality",
])requireText(recorder,needle,"source change recorder")

for(const needle of [
  "/rest-services/family/publication/docdb/",
  "/biblio,legal",
  "EpoPriorityClaim",
  "EpoPrioritySearchClaim",
  "searchEpoPatentFamiliesForReview",
  "searchEpoPublications",
  "buildPrioritySearchTerms",
  'pr any ${cqlTerm(priorityTerms.join(" "))}',
  'ta=${cqlTerm(query)}',
  "uniquePriorityResults.length < requested",
  "hydrateFamilies",
  "parseFamilyMembers",
  "parsePriorityClaims",
  "parseCitations",
  "parseLegalEvents",
  "familyMembers",
  "jurisdictions",
  "priorityClaims",
  "citations",
  "legalEvents",
  "evidenceCoverage",
  'family: "family_endpoint"',
  'priorities: "family_endpoint"',
  'priorities: "source_not_found"',
  'priorities: "unavailable"',
  'family: "equivalents_fallback"',
  'family: "source_not_found"',
  'family: "unavailable"',
  'citations: "unavailable"',
  'legalEvents: "unavailable"',
  "retrievedAt",
])requireText(epo,needle,"EPO OPS evidence client")

for(const needle of [
  "requireUser()",
  "buildPatentPriorArtReview",
  "patent.prior_art_review",
  "Consulta de prior art inválida.",
  'includeGlobal: z.enum(["0", "1"])',
  'url.searchParams.get("global") === "1"',
  "candidates_with_observed_changes",
  "observed_change_events",
  "global_requested",
  "global_availability",
  "global_family_linked_candidates",
])requireText(route,needle,"prior-art API")
if(route.includes("createAdminClient")||route.includes("SUPABASE_SERVICE_ROLE_KEY"))fail("route must authenticate user and delegate server-only enrichment; it must not expose service-role handling")

for(const needle of [
  "Sistema de nanoburbujas de bajo consumo para oxigenar estanques de acuicultura",
  "Potential prior art",
  "Revisión cercana",
  "Vínculos EPO",
  "globalFamilyLinkedCandidates",
  "globalFamilyMatches",
  "EPO link",
  "Familia EPO vinculada por prioridad",
  "Coincidencia observada por país + fecha + número normalizado",
  "Cambios observados",
  "Cambios observados en fuente",
  "Diferencias detectadas entre snapshots INAPI desde el baseline de VIDENTIA. No es la historia jurídica completa.",
  "VIDENTIA conserva diferencias entre snapshots oficiales observados desde",
  "Primera observación",
  "Estado actualizado",
  "Solicitante o titular actualizado",
  "No responde “patentable / no patentable”",
  "Activar EPO OPS",
  "familias, prioridades, jurisdicciones, citas y eventos jurídicos observados",
  'aria-pressed={includeGlobal}',
  "evidenceCoverage",
  "evidenceCoverage.priorities",
  "Cobertura de evidencia",
  "Prioridades EPO observadas",
  "Cobertura de prioridades no disponible para esta familia",
  "Jurisdicciones observadas",
  "Último evento observado",
  "Cobertura de eventos jurídicos no disponible",
  "Citas observadas",
  "Eventos jurídicos observados",
  "No se infiere estado jurídico actual a partir de estos eventos",
  "PatentExternalVerification",
  "applicationNumber={candidate.applicationNumber}",
  "priorityClaims={candidate.priorityClaims}",
  'review.globalEvidence.requested ? "&global=1" : ""',
  "Esto no demuestra ausencia de prior art",
  "Crear reporte",
])requireText(page,needle,"prior-art UI")

for(const needle of [
  "Verificación internacional",
  "Google Patents",
  "PATENTSCOPE",
  "Espacenet",
  "patents.google.com",
  "patentscope.wipo.int",
  "worldwide.espacenet.com",
  "ALLNUM:",
  "Apertura manual; VIDENTIA no automatiza ni scrapea estas interfaces.",
  "primaryPriority",
  "applicationNumber",
])requireText(externalVerification,needle,"external patent verification")

console.log("Patent prior-art regression PASS: local evidence remains canonical, EPO retrieval uses a bounded priority-first search with title/abstract fallback, observed INAPI changes and deterministic EPO links remain traceable, and compliant manual verification links expose Google Patents, PATENTSCOPE and Espacenet without automated scraping or unsupported legal conclusions.")
