-- Phase 14: Notifications & Review Workflow
create table if not exists public.case_review_requests (
  id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases(id) on delete cascade,
  requested_by uuid not null references auth.users(id) on delete cascade, reviewer_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','approved','changes_requested','cancelled')),
  message text, response_note text, created_at timestamptz not null default now(), responded_at timestamptz, updated_at timestamptz not null default now()
);
create table if not exists public.user_notifications (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null, case_id uuid references public.cases(id) on delete cascade,
  kind text not null check (kind in ('review_requested','review_approved','review_changes_requested','mention','action_assigned')),
  title text not null, body text, href text, read_at timestamptz, created_at timestamptz not null default now()
);
create index if not exists case_review_requests_case_idx on public.case_review_requests(case_id,created_at desc);
create index if not exists case_review_requests_reviewer_idx on public.case_review_requests(reviewer_id,status,created_at desc);
create unique index if not exists case_review_requests_one_pending_per_reviewer on public.case_review_requests(case_id,reviewer_id) where status='pending';
create index if not exists user_notifications_user_idx on public.user_notifications(user_id,read_at,created_at desc);
alter table public.case_review_requests enable row level security;
alter table public.user_notifications enable row level security;
create policy case_review_requests_select_accessible on public.case_review_requests for select to authenticated using(public.case_access_role(case_id,auth.uid()) is not null);
create policy user_notifications_select_own on public.user_notifications for select to authenticated using(user_id=auth.uid());
create policy user_notifications_update_own on public.user_notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
revoke insert,update,delete on public.case_review_requests from authenticated,anon;
revoke insert,delete on public.user_notifications from authenticated,anon;
grant select on public.case_review_requests to authenticated;
grant select,update on public.user_notifications to authenticated;
create or replace function public.request_case_review(p_case_id uuid,p_reviewer_id uuid,p_message text default null) returns public.case_review_requests language plpgsql security definer set search_path=public,auth as $$
declare v_role text;v_reviewer_role text;v_row public.case_review_requests;begin v_role:=public.case_access_role(p_case_id,auth.uid());if v_role not in ('owner','editor') then raise exception 'not_allowed';end if;if p_reviewer_id=auth.uid() then raise exception 'self_review_not_allowed';end if;v_reviewer_role:=public.case_access_role(p_case_id,p_reviewer_id);if v_reviewer_role is null then raise exception 'reviewer_not_member';end if;insert into public.case_review_requests(case_id,requested_by,reviewer_id,message) values(p_case_id,auth.uid(),p_reviewer_id,nullif(left(trim(coalesce(p_message,'')),1000),'')) returning * into v_row;return v_row;end $$;
revoke all on function public.request_case_review(uuid,uuid,text) from public;grant execute on function public.request_case_review(uuid,uuid,text) to authenticated;
create or replace function public.respond_case_review(p_review_id uuid,p_decision text,p_note text default null) returns public.case_review_requests language plpgsql security definer set search_path=public,auth as $$
declare v_row public.case_review_requests;v_status text;begin v_status:=case when p_decision='approved' then 'approved' when p_decision='changes_requested' then 'changes_requested' else null end;if v_status is null then raise exception 'invalid_decision';end if;update public.case_review_requests set status=v_status,response_note=nullif(left(trim(coalesce(p_note,'')),2000),''),responded_at=now(),updated_at=now() where id=p_review_id and reviewer_id=auth.uid() and status='pending' returning * into v_row;if v_row.id is null then raise exception 'not_allowed';end if;return v_row;end $$;
revoke all on function public.respond_case_review(uuid,text,text) from public;grant execute on function public.respond_case_review(uuid,text,text) to authenticated;
create or replace function public.cancel_case_review(p_review_id uuid) returns public.case_review_requests language plpgsql security definer set search_path=public,auth as $$
declare v_row public.case_review_requests;begin update public.case_review_requests r set status='cancelled',updated_at=now() where r.id=p_review_id and r.status='pending' and (r.requested_by=auth.uid() or public.case_access_role(r.case_id,auth.uid())='owner') returning * into v_row;if v_row.id is null then raise exception 'not_allowed';end if;return v_row;end $$;
revoke all on function public.cancel_case_review(uuid) from public;grant execute on function public.cancel_case_review(uuid) to authenticated;
create or replace function public.notify_case_review_event() returns trigger language plpgsql security definer set search_path=public as $$ declare v_case_title text;begin select title into v_case_title from public.cases where id=new.case_id;if tg_op='INSERT' then insert into public.user_notifications(user_id,actor_id,case_id,kind,title,body,href) values(new.reviewer_id,new.requested_by,new.case_id,'review_requested','Revisión solicitada',coalesce(v_case_title,'Caso'),'/casos/'||new.case_id||'/revision');elsif tg_op='UPDATE' and old.status is distinct from new.status and new.status in ('approved','changes_requested') then insert into public.user_notifications(user_id,actor_id,case_id,kind,title,body,href) values(new.requested_by,new.reviewer_id,new.case_id,case when new.status='approved' then 'review_approved' else 'review_changes_requested' end,case when new.status='approved' then 'Revisión aprobada' else 'Cambios solicitados' end,coalesce(v_case_title,'Caso'),'/casos/'||new.case_id||'/revision');end if;return new;end $$;
drop trigger if exists trg_case_review_notifications on public.case_review_requests;create trigger trg_case_review_notifications after insert or update on public.case_review_requests for each row execute function public.notify_case_review_event();
create or replace function public.notify_case_collaboration() returns trigger language plpgsql security definer set search_path=public as $$ declare v_case_title text;v_uid uuid;begin select title into v_case_title from public.cases where id=new.case_id;if tg_table_name='case_comments' then foreach v_uid in array new.mentions loop if v_uid<>new.author_id then insert into public.user_notifications(user_id,actor_id,case_id,kind,title,body,href) values(v_uid,new.author_id,new.case_id,'mention','Te mencionaron en un caso',left(new.body,240),'/casos/'||new.case_id||'/equipo');end if;end loop;elsif tg_table_name='case_actions' and new.assigned_to is not null then if tg_op='INSERT' or old.assigned_to is distinct from new.assigned_to then insert into public.user_notifications(user_id,actor_id,case_id,kind,title,body,href) values(new.assigned_to,new.created_by,new.case_id,'action_assigned','Nueva acción asignada',new.title,'/casos/'||new.case_id||'/equipo');end if;end if;return new;end $$;
drop trigger if exists trg_case_comment_notifications on public.case_comments;create trigger trg_case_comment_notifications after insert on public.case_comments for each row execute function public.notify_case_collaboration();drop trigger if exists trg_case_action_notifications on public.case_actions;create trigger trg_case_action_notifications after insert or update of assigned_to on public.case_actions for each row execute function public.notify_case_collaboration();
alter table public.case_events drop constraint if exists case_events_event_type_check;alter table public.case_events add constraint case_events_event_type_check check(event_type in ('case_created','status_changed','priority_changed','decision_changed','notes_changed','review_checkpoint','item_added','item_removed','member_added','member_removed','comment_added','action_added','action_completed','review_requested','review_approved','review_changes_requested','review_cancelled'));
create or replace function public.log_case_review_event() returns trigger language plpgsql security definer set search_path=public as $$ declare v_owner uuid;v_type text;v_title text;begin select user_id into v_owner from public.cases where id=new.case_id;if tg_op='INSERT' then v_type:='review_requested';v_title:='Revisión solicitada';elsif old.status is distinct from new.status then v_type:=case new.status when 'approved' then 'review_approved' when 'changes_requested' then 'review_changes_requested' when 'cancelled' then 'review_cancelled' else null end;v_title:=case new.status when 'approved' then 'Revisión aprobada' when 'changes_requested' then 'Cambios solicitados' when 'cancelled' then 'Revisión cancelada' else null end;end if;if v_type is not null then insert into public.case_events(case_id,user_id,event_type,title,payload,occurred_at) values(new.case_id,v_owner,v_type,v_title,jsonb_build_object('review_id',new.id,'reviewer_id',new.reviewer_id,'requested_by',new.requested_by,'status',new.status),now());end if;return new;end $$;
drop trigger if exists trg_case_review_events on public.case_review_requests;create trigger trg_case_review_events after insert or update on public.case_review_requests for each row execute function public.log_case_review_event();