insert into public.trademark_internal_labels (organization_id, name, slug, category, description, color, is_system)
values
(null, 'Solicitud ingresada', 'solicitud-ingresada', 'case_status', 'Solicitud presentada ante INAPI.', 'secondary', true),
(null, 'En plazo de oposición', 'en-plazo-de-oposicion', 'case_status', 'Publicación vigente con plazo para evaluar oposición.', 'outline', true),
(null, 'Con oposición', 'con-oposicion', 'case_status', 'El expediente registra una oposición.', 'destructive', true),
(null, 'Observada por INAPI', 'observada-por-inapi', 'case_status', 'El expediente tiene una observación pendiente.', 'destructive', true),
(null, 'Rechazada', 'rechazada', 'case_status', 'Solicitud rechazada por la autoridad.', 'destructive', true),
(null, 'Renovación pendiente', 'renovacion-pendiente', 'case_status', 'Registro próximo a vencer y requiere gestión.', 'outline', true),
(null, 'Prioridad crítica', 'prioridad-critica', 'risk', 'Requiere acción inmediata por riesgo o vencimiento.', 'destructive', true),
(null, 'Prioridad alta', 'prioridad-alta', 'risk', 'Debe ser atendido antes que los casos ordinarios.', 'outline', true),
(null, 'Sin conflicto aparente', 'sin-conflicto-aparente', 'relevance', 'No se identifican antecedentes relevantes.', 'secondary', true),
(null, 'Coincidencia exacta', 'coincidencia-exacta', 'relevance', 'Coincidencia denominativa o figurativa muy alta.', 'destructive', true),
(null, 'Coincidencia fonética', 'coincidencia-fonetica', 'relevance', 'Similitud relevante por sonido o pronunciación.', 'outline', true),
(null, 'Coincidencia figurativa', 'coincidencia-figurativa', 'relevance', 'Similitud relevante entre elementos gráficos.', 'outline', true),
(null, 'Producto o servicio relacionado', 'producto-servicio-relacionado', 'relevance', 'Relación comercial entre productos o servicios.', 'outline', true),
(null, 'Preparar oposición', 'preparar-oposicion', 'action', 'Evaluar y preparar oposición dentro de plazo.', 'destructive', true),
(null, 'Solicitar instrucciones', 'solicitar-instrucciones', 'action', 'Requiere decisión o antecedentes del cliente.', 'outline', true),
(null, 'Preparar respuesta a observación', 'preparar-respuesta-observacion', 'action', 'Preparar contestación a observación de INAPI.', 'outline', true),
(null, 'Recomendar modificación', 'recomendar-modificacion', 'action', 'Sugerir ajustes a la marca o cobertura.', 'outline', true),
(null, 'Escalar a abogado senior', 'escalar-abogado-senior', 'action', 'Revisión por abogado con mayor experiencia.', 'destructive', true),
(null, 'Plazo próximo a vencer', 'plazo-proximo-a-vencer', 'monitoring', 'Existe un plazo que requiere seguimiento cercano.', 'outline', true),
(null, 'Plazo crítico', 'plazo-critico', 'monitoring', 'El plazo está próximo a vencer o requiere alerta inmediata.', 'destructive', true),
(null, 'Plazo vencido', 'plazo-vencido', 'monitoring', 'El plazo identificado ya venció.', 'destructive', true),
(null, 'En espera de cliente', 'en-espera-de-cliente', 'case_status', 'El caso no puede avanzar sin instrucciones del cliente.', 'outline', true),
(null, 'En preparación', 'en-preparacion', 'case_status', 'El equipo está preparando una presentación o informe.', 'secondary', true),
(null, 'Pendiente de firma', 'pendiente-de-firma', 'case_status', 'Documento pendiente de firma o aprobación.', 'outline', true),
(null, 'Pendiente de pago', 'pendiente-de-pago', 'case_status', 'Gestión pendiente de pago o provisión.', 'outline', true),
(null, 'Marca estratégica', 'marca-estrategica', 'monitoring', 'Marca prioritaria para el portafolio del cliente.', 'secondary', true),
(null, 'Competidor directo', 'competidor-directo', 'monitoring', 'Titular o marca de un competidor directo.', 'outline', true),
(null, 'Marca defensiva', 'marca-defensiva', 'monitoring', 'Marca mantenida como protección estratégica.', 'secondary', true),
(null, 'Seguimiento semanal', 'seguimiento-semanal', 'monitoring', 'Revisión periódica semanal.', 'outline', true),
(null, 'Seguimiento mensual', 'seguimiento-mensual', 'monitoring', 'Revisión periódica mensual.', 'outline', true)
on conflict (organization_id, slug) do nothing;
