import Link from "next/link"
import { redirect } from "next/navigation"
import { ArrowRight, BellRing, CheckCircle2, ShieldCheck } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { createClient } from "@/lib/supabase/server"

export const dynamic = "force-dynamic"
type CaseRow={id:string;title:string;status:string;priority:string;updated_at:string}
type Policy={case_id:string;enabled:boolean;auto_remind:boolean;auto_raise_priority:boolean;remind_before_hours:number;escalate_before_hours:number;updated_at:string}

export default async function ControlPortfolioPage(){
 const supabase=await createClient();const {data:auth}=await supabase.auth.getUser();if(!auth.user)redirect("/auth/login?redirectTo=%2Fportfolio%2Fcontrol")
 const [casesResult,policiesResult]=await Promise.all([
  supabase.from("cases").select("id,title,status,priority,updated_at").not("status","in",'("decided","archived")').order("updated_at",{ascending:false}).limit(200),
  supabase.from("case_automation_policy").select("case_id,enabled,auto_remind,auto_raise_priority,remind_before_hours,escalate_before_hours,updated_at"),
 ])
 if(casesResult.error||policiesResult.error)throw new Error("No pudimos cargar el centro de control.")
 const cases=(casesResult.data??[]) as CaseRow[];const policies=(policiesResult.data??[]) as Policy[];const map=new Map(policies.map(p=>[p.case_id,p]));const automated=cases.filter(c=>map.get(c.id)?.enabled);const reminderCount=automated.filter(c=>map.get(c.id)?.auto_remind).length;const escalationCount=automated.filter(c=>map.get(c.id)?.auto_raise_priority).length
 return <div className="mx-auto w-full max-w-[1480px] px-4 py-9 sm:px-6 lg:px-8 lg:py-12">
  <header className="grid gap-8 border-b border-border pb-9 lg:grid-cols-[0.82fr_1.18fr] lg:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-primary">VIDENTIA / Portafolio / Control</p><h1 className="mt-4 max-w-[11ch] text-4xl font-normal leading-[0.96] tracking-[-0.05em] text-foreground sm:text-5xl lg:text-6xl">Automatiza seguimiento. Mantén humana la decisión.</h1></div><div className="max-w-2xl lg:justify-self-end"><p className="text-base leading-7 text-muted-foreground sm:text-lg">Controla qué casos tienen reglas de recordatorio o escalamiento. La asistencia de cada expediente puede proponer pasos, pero cerrar, aprobar o cambiar una decisión requiere acción humana.</p><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-[10px] font-semibold uppercase tracking-[0.13em] text-muted-foreground"><span>Reglas explícitas</span><span>Trazabilidad</span><span>Confirmación humana</span></div></div></header>
  <section className="grid border-b border-border sm:grid-cols-2 lg:grid-cols-4"><Metric value={automated.length} label="Reglas activas" detail="Casos con automatización habilitada"/><Metric value={reminderCount} label="Con recordatorios" detail="Avisos por ventana de revisión"/><Metric value={escalationCount} label="Con escalamiento" detail="Prioridad puede elevarse por regla"/><Metric value={cases.length} label="Casos activos" detail="Abiertos o en revisión"/></section>
  <section className="grid gap-10 border-b border-border py-10 xl:grid-cols-[0.7fr_1.3fr]"><aside><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-primary">Límites</p><h2 className="mt-2 text-2xl font-normal tracking-[-0.03em] text-foreground">Qué puede y qué no puede hacer el sistema</h2><div className="mt-5 border-l-2 border-primary/35 pl-4"><div className="flex items-center gap-2 text-sm font-medium text-foreground"><ShieldCheck className="h-4 w-4 text-primary"/>Seguimiento, no decisión</div><p className="mt-3 text-sm leading-6 text-muted-foreground">Las reglas pueden recordar revisores y elevar prioridad dentro de ventanas configuradas.</p><p className="mt-3 text-sm leading-6 text-muted-foreground">La asistencia puede resumir evidencia, detectar brechas y sugerir intervenciones.</p><p className="mt-3 text-sm font-medium leading-6 text-foreground">No puede aprobar, cerrar el caso, reasignar revisores ni registrar una decisión sin acción humana.</p></div></aside><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-primary">Casos activos</p><h2 className="mt-2 text-2xl font-normal tracking-[-0.03em] text-foreground">Configuración por expediente</h2><div className="mt-5 divide-y divide-border border-y border-border">{cases.length?cases.slice(0,50).map(c=>{const p=map.get(c.id);return <Link key={c.id} href={`/casos/${c.id}/control`} className="group grid gap-3 py-5 outline-none hover:bg-secondary/15 focus-visible:bg-secondary/20 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap gap-2">{p?.enabled?<Badge className="rounded-md border-primary/20 bg-primary/[0.07] text-primary hover:bg-primary/[0.07]"><CheckCircle2 className="mr-1 h-3 w-3"/>Reglas activas</Badge>:<Badge variant="outline" className="rounded-md">Seguimiento manual</Badge>}{p?.auto_remind?<span className="inline-flex items-center gap-1 text-xs text-muted-foreground"><BellRing className="h-3.5 w-3.5"/>Recordatorios</span>:null}</div><p className="mt-3 text-sm font-semibold text-foreground">{c.title}</p><p className="mt-1 text-xs text-muted-foreground">Prioridad {priorityLabel(c.priority)} · {statusLabel(c.status)}{p?.enabled?` · recordar ${p.remind_before_hours} h · escalar ${p.escalate_before_hours} h`:""}</p></div><ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1"/></Link>}):<p className="py-8 text-sm text-muted-foreground">No hay casos activos.</p>}</div></div></section>
 </div>
}
function Metric({value,label,detail}:{value:number;label:string;detail:string}){return <div className="border-b border-border py-6 sm:border-b-0 sm:border-r sm:px-5 first:pl-0 last:border-r-0"><p className="text-3xl font-semibold tracking-[-0.03em] text-foreground">{value}</p><p className="mt-1 text-sm font-semibold text-foreground">{label}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div>}
function priorityLabel(value:string){return value==="high"?"alta":value==="low"?"baja":"normal"}
function statusLabel(value:string){return value==="review"?"en revisión":value==="open"?"abierto":value}
